// Mock state.json mid-run snapshot.
// Run nm-20260523-2300, started 23:00 local, ~3h47m elapsed.
// Group 1 mostly done, Group 2 in flight, Group 3 starting.

const NM_DATA = {
  run_id: "nm-20260523-2300",
  started_at: "2026-05-23T23:00:00",
  config: {
    max_agents: 3,
    label: "Triaged",
    model: "claude-opus-4.5",
    deploy: true,
  },
  plan: [
    {
      group: 1,
      deploy: false,
      parallel: ["ABS-90", "ABS-91", "ABS-92"],
    },
    {
      group: 2,
      deploy: false,
      parallel: ["ABS-93", "ABS-94", "ABS-95"],
    },
    {
      group: 3,
      deploy: false,
      parallel: ["ABS-96", "ABS-97", "ABS-98", "ABS-99"],
    },
    {
      group: 4,
      deploy: true,
      parallel: [],
    },
  ],
  issues: {
    "ABS-90": {
      identifier: "ABS-90",
      title: "Fix login redirect loop on Safari iOS",
      status: "merged",
      branch: "agent/ABS-90-safari-login-redirect",
      worktree: "/Users/op/wt/ABS-90",
      ports: { pg: 54320, api: 8090, web: 3090 },
      attempts: 1,
      review_attempts: 1,
      started_at: "2026-05-23T23:00:12",
      completed_at: "2026-05-23T23:34:08",
      merged_at: "2026-05-23T23:41:22",
      error: null,
      summary: "Replaced cookie-based redirect with sessionStorage shim; 4 files changed.",
    },
    "ABS-91": {
      identifier: "ABS-91",
      title: "Pagination cursor off-by-one in /api/orgs",
      status: "merged",
      branch: "agent/ABS-91-orgs-cursor",
      worktree: "/Users/op/wt/ABS-91",
      ports: { pg: 54321, api: 8091, web: 3091 },
      attempts: 1,
      review_attempts: 2,
      started_at: "2026-05-23T23:00:14",
      completed_at: "2026-05-23T23:51:40",
      merged_at: "2026-05-24T00:03:18",
      error: null,
      summary: "Fixed cursor encoding; added regression test for boundary case.",
    },
    "ABS-92": {
      identifier: "ABS-92",
      title: "Add export-to-CSV on invoices table",
      status: "failed",
      branch: "agent/ABS-92-invoices-csv",
      worktree: "/Users/op/wt/ABS-92",
      ports: { pg: 54322, api: 8092, web: 3092 },
      attempts: 2,
      review_attempts: 3,
      started_at: "2026-05-23T23:00:16",
      completed_at: "2026-05-24T00:18:44",
      merged_at: null,
      error: "E2E test failed: invoice-export.spec.ts timeout after 30s. Streaming response never closed.",
      summary: null,
    },
    "ABS-93": {
      identifier: "ABS-93",
      title: "Sentry breadcrumbs missing user context",
      status: "merged",
      branch: "agent/ABS-93-sentry-user",
      worktree: "/Users/op/wt/ABS-93",
      ports: { pg: 54323, api: 8093, web: 3093 },
      attempts: 1,
      review_attempts: 1,
      started_at: "2026-05-24T00:05:02",
      completed_at: "2026-05-24T00:48:30",
      merged_at: "2026-05-24T00:56:11",
      error: null,
      summary: "Hooked Sentry init to auth context. 2 files changed.",
    },
    "ABS-94": {
      identifier: "ABS-94",
      title: "Migrate billing webhook to idempotent handler",
      status: "reviewing",
      branch: "agent/ABS-94-billing-idempotent",
      worktree: "/Users/op/wt/ABS-94",
      ports: { pg: 54324, api: 8094, web: 3094 },
      attempts: 1,
      review_attempts: 2,
      started_at: "2026-05-24T00:18:11",
      completed_at: "2026-05-24T02:14:55",
      merged_at: null,
      error: null,
      summary: "Awaiting review pass 2 — reviewer flagged missing dedupe key on retry path.",
    },
    "ABS-95": {
      identifier: "ABS-95",
      title: "Dashboard widget loading state flicker",
      status: "in_progress",
      branch: "agent/ABS-95-widget-flicker",
      worktree: "/Users/op/wt/ABS-95",
      ports: { pg: 54325, api: 8095, web: 3095 },
      attempts: 1,
      review_attempts: 0,
      started_at: "2026-05-24T01:42:08",
      completed_at: null,
      merged_at: null,
      error: null,
      currentTool: "Edit",
      currentTarget: "web/components/widgets/SalesCard.tsx",
      summary: null,
    },
    "ABS-96": {
      identifier: "ABS-96",
      title: "Stripe metadata not flowing to ledger entries",
      status: "in_progress",
      branch: "agent/ABS-96-stripe-ledger-meta",
      worktree: "/Users/op/wt/ABS-96",
      ports: { pg: 54326, api: 8096, web: 3096 },
      attempts: 1,
      review_attempts: 0,
      started_at: "2026-05-24T02:31:44",
      completed_at: null,
      merged_at: null,
      error: null,
      currentTool: "Bash",
      currentTarget: "pytest tests/billing/test_ledger.py -k stripe",
      summary: null,
    },
    "ABS-97": {
      identifier: "ABS-97",
      title: "Add organization-scoped API tokens",
      status: "in_progress",
      branch: "agent/ABS-97-org-tokens",
      worktree: "/Users/op/wt/ABS-97",
      ports: { pg: 54327, api: 8097, web: 3097 },
      attempts: 1,
      review_attempts: 0,
      started_at: "2026-05-24T02:32:01",
      completed_at: null,
      merged_at: null,
      error: null,
      currentTool: "Read",
      currentTarget: "api/auth/tokens.py",
      summary: null,
    },
    "ABS-98": {
      identifier: "ABS-98",
      title: "Cron job to vacuum stale upload sessions",
      status: "queued",
      branch: null,
      worktree: null,
      ports: null,
      attempts: 0,
      review_attempts: 0,
      started_at: null,
      completed_at: null,
      merged_at: null,
      error: null,
      summary: null,
    },
    "ABS-99": {
      identifier: "ABS-99",
      title: "Notification preferences UI: opt-out per channel",
      status: "queued",
      branch: null,
      worktree: null,
      ports: null,
      attempts: 0,
      review_attempts: 0,
      started_at: null,
      completed_at: null,
      merged_at: null,
      error: null,
      summary: null,
    },
  },
};

// Log streams for the in_progress agents. Each event has a synthetic offset (ms
// from agent start) so the dashboard can pace them on the live ticker.
const NM_LOGS = {
  "ABS-95": [
    { t: "00:00:04", kind: "tool", name: "Read", args: "web/components/widgets/SalesCard.tsx" },
    { t: "00:00:06", kind: "tool", name: "Read", args: "web/hooks/useWidgetData.ts" },
    { t: "00:00:12", kind: "assistant", text: "The flicker is caused by the loading boundary unmounting between transitions. I'll memoize the skeleton and gate it behind a 120ms threshold." },
    { t: "00:00:18", kind: "tool", name: "Grep", args: "pattern=\"isLoading\\|isPending\" path=web/components/widgets" },
    { t: "00:00:24", kind: "tool", name: "Edit", args: "web/components/widgets/SalesCard.tsx (+18 -6)" },
    { t: "00:00:31", kind: "tool", name: "Edit", args: "web/components/widgets/RevenueCard.tsx (+14 -4)" },
    { t: "00:00:38", kind: "tool", name: "Bash", args: "pnpm test web/components/widgets --watch=false" },
    { t: "00:00:55", kind: "assistant", text: "All 14 widget tests pass. Running the Playwright smoke now to confirm the visual flicker is gone." },
    { t: "00:01:02", kind: "tool", name: "Bash", args: "pnpm exec playwright test e2e/widgets.spec.ts" },
    { t: "00:01:09", kind: "tool", name: "Edit", args: "web/components/widgets/SalesCard.tsx (+3 -1)" },
  ],
  "ABS-96": [
    { t: "00:00:02", kind: "tool", name: "Read", args: "api/billing/stripe_webhook.py" },
    { t: "00:00:05", kind: "tool", name: "Read", args: "api/billing/ledger.py" },
    { t: "00:00:11", kind: "tool", name: "Grep", args: "pattern=\"metadata\" path=api/billing" },
    { t: "00:00:16", kind: "assistant", text: "Metadata is parsed in the webhook but dropped before reaching ledger.create(). I need to thread it through the LedgerEntry constructor and the migration." },
    { t: "00:00:22", kind: "tool", name: "Edit", args: "api/billing/ledger.py (+22 -3)" },
    { t: "00:00:28", kind: "tool", name: "Bash", args: "alembic revision --autogenerate -m add_metadata_to_ledger" },
    { t: "00:00:34", kind: "tool", name: "Edit", args: "api/billing/stripe_webhook.py (+9 -2)" },
    { t: "00:00:41", kind: "tool", name: "Bash", args: "pytest tests/billing/test_ledger.py -k stripe" },
  ],
  "ABS-97": [
    { t: "00:00:01", kind: "tool", name: "Read", args: "api/auth/tokens.py" },
    { t: "00:00:03", kind: "tool", name: "Read", args: "api/auth/models.py" },
    { t: "00:00:06", kind: "tool", name: "Read", args: "api/auth/routes.py" },
    { t: "00:00:09", kind: "assistant", text: "Existing tokens are user-scoped. I'll add an `org_id` column with backfill, a new POST /orgs/{id}/tokens route, and scope middleware that prefers org membership when org_id is set." },
    { t: "00:00:14", kind: "tool", name: "Read", args: "api/orgs/membership.py" },
  ],
  "ABS-94": [
    { t: "00:00:00", kind: "tool", name: "Read", args: "api/billing/webhook.py" },
    { t: "00:00:04", kind: "tool", name: "Edit", args: "api/billing/webhook.py (+42 -11)" },
    { t: "00:00:09", kind: "tool", name: "Bash", args: "pytest tests/billing/" },
    { t: "00:00:15", kind: "tool", name: "Bash", args: "pnpm exec playwright test e2e/billing.spec.ts" },
    { t: "00:00:21", kind: "assistant", text: "Initial pass complete. Submitting for review." },
    { t: "00:00:25", kind: "review", text: "Review v1 — found 1 issue: dedupe_key not persisted across retry attempts. Recommend rework." },
    { t: "00:00:28", kind: "tool", name: "Edit", args: "api/billing/webhook.py (+8 -2)" },
    { t: "00:00:34", kind: "review", text: "Review v2 in progress…" },
  ],
};

// NM-level system log
const NM_SYSTEM_LOG = [
  { t: "23:00:00", level: "info", msg: "Night Manager started · run_id=nm-20260523-2300" },
  { t: "23:00:00", level: "info", msg: "Fetched 10 issues with label \"Triaged\" from Linear" },
  { t: "23:00:01", level: "info", msg: "Planned 4 groups · max_agents=3 · deploy=true" },
  { t: "23:00:12", level: "info", msg: "Group 1 started · 3 agents" },
  { t: "23:34:08", level: "info", msg: "ABS-90 completed coding (33m 56s)" },
  { t: "23:41:22", level: "ok",   msg: "ABS-90 merged to dev" },
  { t: "23:51:40", level: "info", msg: "ABS-91 completed coding (51m 26s)" },
  { t: "00:03:18", level: "ok",   msg: "ABS-91 merged to dev" },
  { t: "00:05:02", level: "info", msg: "Group 2 started · 3 agents" },
  { t: "00:18:44", level: "warn", msg: "ABS-92 failed E2E · invoice-export.spec.ts timeout" },
  { t: "00:21:09", level: "warn", msg: "ABS-92 retry 1/2 spawned" },
  { t: "00:48:30", level: "info", msg: "ABS-93 completed coding (43m 28s)" },
  { t: "00:56:11", level: "ok",   msg: "ABS-93 merged to dev" },
  { t: "01:42:08", level: "info", msg: "ABS-95 spawned" },
  { t: "02:14:55", level: "info", msg: "ABS-94 entered review (v2)" },
  { t: "02:31:44", level: "info", msg: "Group 3 started · 3 agents (ABS-98 queued)" },
];

// Past reports for the report viewer
const NM_REPORTS = [
  { id: "report-2026-05-22-2300", date: "May 22, 2026 · 23:00", merged: 8, failed: 1, blocked: 0, duration: "5h 12m" },
  { id: "report-2026-05-21-2300", date: "May 21, 2026 · 23:00", merged: 11, failed: 0, blocked: 1, duration: "6h 48m" },
  { id: "report-2026-05-20-2300", date: "May 20, 2026 · 23:00", merged: 6, failed: 2, blocked: 0, duration: "4h 02m" },
  { id: "report-2026-05-19-2300", date: "May 19, 2026 · 23:00", merged: 9, failed: 1, blocked: 1, duration: "5h 45m" },
  { id: "report-2026-05-18-2300", date: "May 18, 2026 · 23:00", merged: 5, failed: 3, blocked: 0, duration: "3h 51m" },
];

// Linear-fetched preview issues for the Launch screen
const NM_TRIAGED = [
  { id: "ABS-100", title: "Investigate slow query on /reports/aggregate", est: "M" },
  { id: "ABS-101", title: "Stripe webhook signature mismatch in staging", est: "S" },
  { id: "ABS-102", title: "Add Slack notification for new signups", est: "S" },
  { id: "ABS-103", title: "Refactor org-switcher dropdown component", est: "M" },
  { id: "ABS-104", title: "Audit log retention: drop > 90 day rows nightly", est: "S" },
  { id: "ABS-105", title: "Bug: timezone offset wrong on weekly digest emails", est: "S" },
  { id: "ABS-106", title: "Onboarding: skip-for-now affordance on tour step 3", est: "S" },
  { id: "ABS-107", title: "API rate limit headers should include reset epoch", est: "S" },
  { id: "ABS-108", title: "Add CSV import path for Contacts module", est: "L" },
];

Object.assign(window, { NM_DATA, NM_LOGS, NM_SYSTEM_LOG, NM_REPORTS, NM_TRIAGED });
