"""Structured report deliverable (ABS-342).

A purchased answer is the headline "report SKU" — but the engine produces
*markdown*. This module maps that engine output into the typed
``ReportContent`` schema the frontend ``ReportDocument`` template renders:
a letterhead + title + meta grid + determination band + summary + a typed
**block array** + a verification footer.

The block array is the heart of it — a small, closed set of block types
(``keyvals | uses | finding | table | flags | prose``) rendered by one
shared switch on the client, so no report type carries its own layout
code. This module is the server side of that contract: it parses the
markdown answer into those blocks and derives the report envelope
(verdict, summary, ref, and the letterhead/footer meta lifted off the
purchase record) so the client renders pure data.

Deliberately conservative: an answer whose markdown we can't confidently
decompose still yields a valid report — a single ``prose`` block carrying
the full answer — so the deliverable never regresses below today's raw
markdown. The verdict falls back to a neutral ``attention`` band when the
text carries no determination signal.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime

from advisor.billing.questions import question_for
from advisor.db.models import QuestionPurchase

# -- Lifted letterhead / footer literals (ABS-342) --------------------------
# The design handoff hardcoded these in the report chrome. They are report
# *data*, not layout, so they live here (and, where per-report, on the
# purchase record) and travel to the client in the report envelope.
BYLAW_VERSION = "HRM Regional Centre Land Use By-law — 2024 consolidation"
DEFAULT_ZONE_SUBTITLE = "Established Residential, Type 1"
FOOTER_TEMPLATE = (
    "This report was generated by ABS° and grounded in the {bylaw_version}. "
    "Reference {ref}, issued {issued}. It is a preliminary planning aid, not "
    "an official municipal determination — verify the governing provisions "
    "before relying on it."
)

# Per-question reference prefix. The ref is a human-facing report id
# ("DD-000321"); the prefix keys off the question so a customer can tell a
# due-diligence report from a compliance check at a glance.
_REF_PREFIX = {
    "permitted_use": "PU",
    "development_standards": "DS",
    "due_diligence": "DD",
    "legal_nonconforming": "NC",
    "variance_justification": "VJ",
    "other": "GR",
}


# -- Verdict classification -------------------------------------------------
# statusInfo() on the client centralizes color/tag; the server side is
# choosing WHICH status a report carries. `pass` is the only "green"
# (accent) determination; everything adverse (fail / conditional /
# attention) renders in brick.
#
# The *status* (pass / conditional / fail / attention) is content-derived
# and shared across report types — it drives colour. The *label* is the
# headline verdict line, and a permitted-use frame ("Permitted with
# conditions") reads as a template artifact on a report that concludes on
# something else (a variance package concludes on statutory-test
# *supportability*, not use-permission). So the label is tailored per
# report type's question below, keyed by the same content-derived status
# (ABS-365).
# A variance package can conclude that the requirement it was asked to justify
# is *already met* — the resolved standard leaves nothing to vary, so no
# variance is required at all (ABS-377). That is a determination in its own
# right, distinct from "supportable" (pass): the report is telling the
# applicant their variance premise is moot, not blessing a variance on its
# merits. It MUST win over every other signal, because such an answer routinely
# also states the setback "complies" / "is permitted" (a `pass` signal) or
# rebuts a "does not comply" premise (a `fail` signal) — classifying on those
# would paint the misleading "PASS — Supportable" band the ticket flags. So
# this is checked first in `_classify_status`.
_NOT_REQUIRED_SIGNALS = (
    "no variance is required",
    "no variance required",
    "variance is not required",
    "variance may not be required",
    "variance is not needed",
    "no variance is needed",
    "variance not required",
)
_FAIL_SIGNALS = (
    "not permitted",
    "prohibited",
    "does not comply",
    "non-compliant",
    "fails",
    "fail",
    "violation",
)
_CONDITIONAL_SIGNALS = (
    "conditional",
    "subject to",
    "permitted with conditions",
    "requires a variance",
    "requires approval",
    "development permit required",
)
_PASS_SIGNALS = (
    "permitted as-of-right",
    "permitted as of right",
    "as-of-right",
    "is permitted",
    "complies",
    "compliant",
    "meets the",
    "conforms",
)


@dataclass(frozen=True)
class _Verdict:
    status: str
    label: str


# Per-report-type headline labels, keyed by content-derived status. Each
# question concludes on its *own* question ("is the use permitted?" vs "does
# it comply?" vs "is the variance supportable?"), so the four status bands
# get a label phrased in that report's own frame. The status polarity is
# constant — `pass` is the favourable outcome for the report, `fail` the
# adverse one, `conditional` the qualified one, `attention` the neutral
# "no clear determination" band — only the wording changes.
_VERDICT_LABELS: dict[str, dict[str, str]] = {
    "permitted_use": {
        "pass": "Permitted as-of-right",
        "conditional": "Permitted with conditions",
        "fail": "Not permitted",
        "attention": "Review required",
    },
    "development_standards": {
        "pass": "Complies with all standards",
        "conditional": "Complies subject to conditions",
        "fail": "Does not comply",
        "attention": "Review required",
    },
    "due_diligence": {
        "pass": "No material issues identified",
        "conditional": "Proceed with conditions",
        "fail": "Material concerns identified",
        "attention": "Review required",
    },
    "legal_nonconforming": {
        "pass": "Legally non-conforming (protected)",
        "conditional": "Protected, subject to conditions",
        "fail": "Not protected — non-compliant",
        "attention": "Review required",
    },
    "variance_justification": {
        "pass": "Supportable on all three statutory tests",
        "conditional": "Supportable with conditions",
        "fail": "Not supportable",
        "attention": "Supportability unclear",
        # ABS-377: the resolved requirement is already met, so the variance
        # the package was asked to justify is moot. The chip reads NOT REQUIRED
        # (client statusInfo); this headline explains why.
        "not_required": "Resolved requirement already met — no variance needed",
    },
}
# Neutral fallback frame for any unknown / off-menu ("other") report type —
# the pre-ABS-365 use-permission wording, which is a safe generic default.
_DEFAULT_VERDICT_LABELS: dict[str, str] = {
    "pass": "Permitted as-of-right",
    "conditional": "Permitted with conditions",
    "fail": "Does not comply",
    "attention": "Review required",
    # Generic frame for the ABS-377 not-required band on a non-variance report
    # type. In practice only variance packages emit "no variance required"
    # phrasing, but keep a default so `_label_for` never KeyErrors on it.
    "not_required": "Requirement already met — no variance needed",
}


def _classify_status(answer: str) -> str:
    """Derive the determination *status* (colour band) from the answer text.

    A "no variance required" conclusion wins over everything (ABS-377): it is
    the report's central determination and such answers routinely also carry
    pass/fail keywords that would otherwise mispaint the band. After that,
    adverse signals win over favourable ones (a report that says "permitted
    but the rear setback fails" is not a clean pass). Falls back to a
    neutral ``attention`` band — a report with no determination keyword is
    informational, still rendered in the adverse (brick) palette so it never
    misreads as a green all-clear.
    """
    lowered = answer.lower()
    if any(sig in lowered for sig in _NOT_REQUIRED_SIGNALS):
        return "not_required"
    if any(sig in lowered for sig in _FAIL_SIGNALS):
        return "fail"
    if any(sig in lowered for sig in _CONDITIONAL_SIGNALS):
        return "conditional"
    if any(sig in lowered for sig in _PASS_SIGNALS):
        return "pass"
    return "attention"


def _label_for(status: str, question_slug: str | None) -> str:
    """Tailor the headline verdict label to the report type's question."""
    labels = _VERDICT_LABELS.get(question_slug or "", _DEFAULT_VERDICT_LABELS)
    return labels.get(status, _DEFAULT_VERDICT_LABELS[status])


def _classify_verdict(answer: str, question_slug: str | None = None) -> _Verdict:
    """Derive the determination band (status + report-typed label).

    The status is content-derived and shared across report types; the label
    is phrased in the report's own frame (ABS-365). ``question_slug=None``
    (e.g. a within-report ``finding`` callout, which uses only the status)
    falls back to the neutral use-permission wording.
    """
    status = _classify_status(answer)
    return _Verdict(status, _label_for(status, question_slug))


# -- Markdown → block parsing -----------------------------------------------

_HEADING_RE = re.compile(r"^\s{0,3}(#{1,6})\s+(.*\S)\s*$")
# A markdown horizontal rule on its own line: `---`, `***`, `___`, or their
# spaced variants (`- - -`). The engine emits these both as the fence
# between its planning monologue and the report proper, and as decorative
# dividers between sections. This renderer has no "rule" block, so a stray
# rule can only leak as literal `---` text in a summary/prose block — noise
# on a paid, exportable deliverable (ABS-359).
_HRULE_RE = re.compile(r"^\s{0,3}([-*_])(?:\s*\1){2,}\s*$")

# First-person conversational chatter the agent emits around the report — the
# planning monologue it "thinks out loud" before writing ("I have gathered the
# key provisions … Let me compile the findings:", "Based on my research, I can
# now provide you with a complete answer:") and the sign-off it tacks on after
# ("I apologize that I cannot provide … Would you like me to research a
# different property?"). None of it belongs in a formal, paid deliverable, so
# it is scrubbed from the lead AND the body — leading, trailing, or fenced by a
# stray horizontal rule (ABS-359). A closed allowlist of phrasings was too
# brittle (it missed "Based on my research …"); this set targets the
# first-person meta-talk a report written in the impersonal third person never
# contains.
_MONOLOGUE_SIGNALS = (
    # Planning / "I now have what I need" preambles.
    "let me compile",
    "compile the findings",
    "compile the answer",
    "i have gathered",
    "i have enough",
    "i now have",
    "i have sufficient",
    "sufficient information",
    "have the full picture",
    "have the complete picture",
    "let me prepare",
    "let me put together",
    "let me lay out",
    "let me answer",
    "now i have",
    "here is the report",
    "here's the report",
    "here is my",
    "here's my",
    # "Based on my research I can now answer" transitions into the report.
    "based on my research",
    "based on my analysis",
    "i can now provide",
    "i can now answer",
    "provide you with a complete answer",
    "provide you with an answer",
    "provide you with a definitive",
    "i need to flag",
    # Conversational sign-offs / apologies tacked on after the report.
    "i apologize",
    "i cannot provide",
    "i'm unable to",
    "i am unable to",
    "would you like me to",
    "would you like",
    "let me know if",
    "feel free to",
    "if you'd like",
    "if you would like",
    "happy to help",
    "hope this helps",
    "hope that helps",
)

# Split prose into sentences on terminal punctuation (incl. the trailing colon
# the agent uses to introduce a report: "… Let me compile the findings:").
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?:])\s+")


def _is_hrule(line: str) -> bool:
    return bool(_HRULE_RE.match(line))


def _looks_like_monologue(text: str) -> bool:
    """True when a paragraph reads as the agent's conversational chatter."""
    lowered = text.lower()
    return any(sig in lowered for sig in _MONOLOGUE_SIGNALS)


def _scrub_monologue(text: str) -> str:
    """Drop agent chatter sentence-by-sentence, keeping real report prose.

    Monologue rides in as whole sentences ("I apologize that I cannot provide
    a definitive citation-grounded answer.") that sit beside legitimate report
    text ("The variance is supportable."), sometimes on the same line. Working
    per line, then per sentence, lets us keep the substance and drop only the
    chatter — a paragraph that is entirely monologue collapses to "".
    """
    kept_lines: list[str] = []
    for line in text.split("\n"):
        sentences = _SENTENCE_SPLIT_RE.split(line)
        kept = [
            s for s in sentences if s.strip() and not _looks_like_monologue(s)
        ]
        if kept:
            kept_lines.append(" ".join(kept))
    return "\n".join(kept_lines).strip()


def _strip_preamble(lines: list[str]) -> list[str]:
    """Drop the agent's opening monologue and its separating horizontal rule.

    The engine fences its planning monologue off from the report proper with
    a horizontal rule that sits *before the first heading*
    (``… Let me compile the findings:`` → ``---`` → ``# Variance …``). If such
    a rule exists ahead of the first heading, everything up to and including
    it is scaffolding — the report starts after it. A well-formed report's
    lead paragraph flows straight into its first heading with no rule between,
    so this never eats real summary text.
    """
    first_heading = next(
        (i for i, ln in enumerate(lines) if _HEADING_RE.match(ln)), len(lines)
    )
    last_rule = None
    for i in range(first_heading):
        if _is_hrule(lines[i]):
            last_rule = i
    if last_rule is not None:
        return lines[last_rule + 1 :]
    return lines
_TABLE_ROW_RE = re.compile(r"^\s*\|(.+)\|\s*$")
_TABLE_SEP_RE = re.compile(r"^\s*\|?[\s:|-]+\|?\s*$")
_BULLET_RE = re.compile(r"^\s*[-*]\s+(.*\S)\s*$")
# `**Label:** value` or `- **Label:** value`
_KEYVAL_RE = re.compile(r"^\s*(?:[-*]\s+)?\*\*(.+?)\*\*\s*:?\s*(.*)$")

_USE_STATUS = {
    "permitted": ("permitted", "pass"),
    "as-of-right": ("permitted", "pass"),
    "as of right": ("permitted", "pass"),
    "conditional": ("conditional", "conditional"),
    "prohibited": ("prohibited", "fail"),
    "not permitted": ("prohibited", "fail"),
}
_ROW_PASS = ("pass", "complies", "meets", "conforms")
_ROW_EXCEEDS = ("exceeds", "better than", "above minimum", "surpasses")
_ROW_FAIL = ("fail", "exceeds maximum", "does not comply", "over", "non-compliant")
# A row whose verdict is N/A / not-regulated / uncertain carries NO
# determination, so it renders no pill. These are checked before the
# PASS/EXCEEDS/FAIL signals so a neutral verdict can't false-positive on a
# status substring — e.g. "Lot Coverage" contains "over" (a _ROW_FAIL
# signal), which used to paint a contradictory FAIL pill next to a
# "N/A — no maximum" verdict (ABS-373). The FAR row ("N/A (no limit)") had no
# such substring, so the derivation was inconsistent, not just lenient.
_ROW_NEUTRAL = (
    "not regulated",
    "no maximum",
    "no limit",
    "not applicable",
    "uncertain",
)
# A table only carries per-row PASS/FAIL semantics if its header names an
# actual evaluation column (e.g. the development-standards "Result" column).
# Without this gate, `_row_status` scans every cell of every table — including
# plain field/value property-summary tables — and false-positives on
# ordinary label text (e.g. "over" inside "Governing By-law") (ABS-366).
_STATUS_COLUMN_SIGNALS = (
    "result",
    "status",
    "compliance",
    "verdict",
    "determination",
    "outcome",
    "pass/fail",
)
_FLAG_HEADINGS = ("flag", "non-conform", "concern", "warning", "risk", "issue")
_USE_HEADINGS = ("use", "permitted", "conditional")
_FINDING_HEADINGS = (
    "finding",
    "determination",
    "assessment",
    "conclusion",
    "verdict",
)


def _strip_inline(text: str) -> str:
    """Drop markdown emphasis so block payloads are plain strings."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)\*", r"\1", text)
    return text.strip()


def _row_status(cells: list[str]) -> str | None:
    """Per-row PASS / EXCEEDS / FAIL status inferred from a status-ish cell.

    The ``development_standards`` table is the driving case: each standard
    row carries a PASS or EXCEEDS verdict. We scan every cell so the status
    column can sit anywhere.
    """
    joined = " ".join(cells).lower()
    # N/A / not-regulated / uncertain rows carry no determination (ABS-373).
    # Checked first: a cell whose verdict starts with "N/A", or names a
    # not-regulated standard, must never inherit a PASS/FAIL pill.
    if any(cell.strip().lower().startswith("n/a") for cell in cells):
        return None
    if any(sig in joined for sig in _ROW_NEUTRAL):
        return None
    if any(sig in joined for sig in _ROW_EXCEEDS):
        return "exceeds"
    if any(sig in joined for sig in _ROW_FAIL):
        return "fail"
    if any(sig in joined for sig in _ROW_PASS):
        return "pass"
    return None


def _use_status(text: str) -> tuple[str, str] | None:
    lowered = text.lower()
    for needle, (label, status) in _USE_STATUS.items():
        if needle in lowered:
            return label, status
    return None


def _parse_table(lines: list[str]) -> dict | None:
    """Turn a contiguous markdown table into a ``table`` block."""
    rows = [ln for ln in lines if _TABLE_ROW_RE.match(ln)]
    if len(rows) < 2:
        return None

    def cells(line: str) -> list[str]:
        inner = _TABLE_ROW_RE.match(line).group(1)
        return [_strip_inline(c) for c in inner.split("|")]

    header = cells(rows[0])
    is_evaluation_table = any(
        sig in h.lower() for h in header for sig in _STATUS_COLUMN_SIGNALS
    )
    body = [r for r in rows[1:] if not _TABLE_SEP_RE.match(r)]
    out_rows = []
    for r in body:
        cvals = cells(r)
        status = _row_status(cvals) if is_evaluation_table else None
        out_rows.append({"cells": cvals, "status": status})
    if not out_rows:
        return None
    return {"type": "table", "columns": header, "rows": out_rows}


def _parse_section(heading: str | None, lines: list[str]) -> list[dict]:
    """Parse one heading section's lines into zero or more blocks."""
    body = [ln for ln in lines if ln.strip()]
    if not body:
        return []

    # A markdown table anywhere in the section becomes a table block; the
    # surrounding prose (if any) is emitted around it in order.
    if any(_TABLE_ROW_RE.match(ln) and "|" in ln for ln in body):
        table_lines = [ln for ln in body if _TABLE_ROW_RE.match(ln)]
        table = _parse_table(table_lines)
        if table is not None:
            if heading:
                table["title"] = heading
            return [table]

    bullets = [m.group(1) for ln in body if (m := _BULLET_RE.match(ln))]
    hl = (heading or "").lower()

    # Key/value pairs — "**Label:** value" lines (bulleted or not).
    keyvals = []
    for ln in body:
        m = _KEYVAL_RE.match(ln)
        if m and m.group(2).strip():
            key = _strip_inline(m.group(1)).rstrip(":").strip()
            keyvals.append({"k": key, "v": _strip_inline(m.group(2))})
    if keyvals and len(keyvals) == len([ln for ln in body if _KEYVAL_RE.match(ln)]):
        block = {"type": "keyvals", "items": keyvals}
        if heading:
            block["title"] = heading
        return [block]

    if bullets and len(bullets) == len(body):
        # A bulleted section: uses (if items carry use-status), flags (if the
        # heading signals non-conformity), else prose fallback.
        use_items = []
        for b in bullets:
            st = _use_status(b)
            if st is not None:
                label, status = st
                # Use name is the text before any dash/colon separator.
                name = re.split(r"[—:–-]", _strip_inline(b), maxsplit=1)[0].strip()
                use_items.append({"use": name or _strip_inline(b), "status": label, "note": None})
        if use_items and (any(k in hl for k in _USE_HEADINGS) or len(use_items) == len(bullets)):
            block = {"type": "uses", "items": use_items}
            if heading:
                block["title"] = heading
            return [block]

        if any(k in hl for k in _FLAG_HEADINGS):
            flag_items = []
            for b in bullets:
                st = _use_status(b)
                status = st[1] if st else "attention"
                flag_items.append({"status": status, "text": _strip_inline(b)})
            block = {"type": "flags", "items": flag_items}
            if heading:
                block["title"] = heading
            return [block]

    # A determination-style section (no bullets/table/keyvals) becomes a
    # highlighted `finding` callout carrying the section's own verdict.
    text = "\n".join(_strip_inline(ln) for ln in body)
    if any(k in hl for k in _FINDING_HEADINGS):
        return [
            {
                "type": "finding",
                "title": heading,
                "status": _classify_status(text),
                "body": text,
            }
        ]

    # Everything else is prose.
    block = {"type": "prose", "text": text}
    if heading:
        block["title"] = heading
    return [block]


def parse_blocks(answer: str) -> tuple[str, list[dict]]:
    """Split a markdown answer into ``(summary, blocks)``.

    The summary is the lead — the text before the first heading (or the
    first paragraph if the answer is heading-less). Everything after is
    decomposed section-by-section into typed blocks. A heading-less,
    structure-less answer degrades to one prose block so the report is
    always valid.
    """
    lines = answer.replace("\r\n", "\n").split("\n")
    # Strip the agent's opening monologue (fenced by a leading horizontal
    # rule), then drop every remaining stray rule so no `---` survives into a
    # summary or prose block (ABS-359).
    lines = _strip_preamble(lines)
    lines = [ln for ln in lines if not _is_hrule(ln)]

    # Lead paragraph → summary (until the first heading or blank-line break).
    summary_lines: list[str] = []
    idx = 0
    while idx < len(lines):
        if _HEADING_RE.match(lines[idx]):
            break
        if not lines[idx].strip() and summary_lines:
            break
        if lines[idx].strip():
            summary_lines.append(lines[idx])
        idx += 1
    # Second-line defence: even with no fencing rule, a lead carrying the
    # agent's chatter ("Based on my research, I can now provide …") is not a
    # summary — scrub the chatter sentence-by-sentence, keeping any real lead
    # text and collapsing a pure-monologue lead to "" (ABS-359).
    summary = _scrub_monologue(_strip_inline(" ".join(summary_lines)).strip())

    # Sections keyed by heading.
    blocks: list[dict] = []
    heading: str | None = None
    buf: list[str] = []

    def flush() -> None:
        nonlocal buf, heading
        blocks.extend(_parse_section(heading, buf))
        buf = []

    for ln in lines[idx:]:
        m = _HEADING_RE.match(ln)
        if m:
            flush()
            heading = _strip_inline(m.group(2))
        else:
            buf.append(ln)
    flush()

    # Scrub agent chatter out of every prose payload — the sign-off the engine
    # tacks onto its final section ("I apologize that I cannot provide … Would
    # you like me to research a different property?") rides into a prose or
    # finding block's body, not just the lead. A block whose body is entirely
    # chatter is dropped; a finding's status is re-derived from the kept text
    # so a scrubbed apology can't skew the callout's colour (ABS-359).
    scrubbed: list[dict] = []
    for block in blocks:
        if block.get("type") == "prose":
            text = _scrub_monologue(block.get("text", ""))
            if not text:
                continue
            block = {**block, "text": text}
        elif block.get("type") == "finding":
            body = _scrub_monologue(block.get("body", ""))
            if not body:
                continue
            block = {**block, "body": body, "status": _classify_status(body)}
        scrubbed.append(block)
    blocks = scrubbed

    # If the report opens straight into its title heading with no lead
    # paragraph before it, the intro paragraph of that first section IS the
    # lead — promote it so the deliverable always leads with a clean sentence
    # rather than an empty gap (ABS-359).
    if not summary and blocks and blocks[0].get("type") == "prose":
        summary = blocks[0].get("text", "")
        blocks = blocks[1:]

    if not summary and not blocks:
        # Nothing parsed — fall back to the cleaned remaining text (preamble
        # and rules already removed) rather than the raw answer, so no
        # scaffolding re-enters the deliverable.
        remainder = _scrub_monologue(
            _strip_inline(" ".join(ln for ln in lines if ln.strip())).strip()
        )
        if remainder:
            summary = remainder
    if not blocks and answer.strip():
        # No sections parsed — carry the cleaned remainder as prose so the
        # deliverable never falls below raw markdown (minus the scaffolding).
        remainder = _scrub_monologue(_strip_inline("\n".join(lines)).strip())
        if remainder and remainder != summary:
            blocks.append({"type": "prose", "text": remainder})
    return summary, blocks


# -- Envelope builder -------------------------------------------------------


def _ref_for(purchase: QuestionPurchase) -> str:
    prefix = _REF_PREFIX.get(purchase.question_slug, "GR")
    return f"{prefix}-{purchase.id:06d}"


def _report_type(purchase: QuestionPurchase) -> str:
    try:
        return question_for(purchase.question_slug).display_name
    except KeyError:
        return "Bylaw report"


def _issued(purchase: QuestionPurchase) -> str:
    dt = purchase.settled_at or purchase.answered_at
    if isinstance(dt, datetime):
        return dt.date().isoformat()
    return ""


_ZONE_PAREN_RE = re.compile(r"^(\S+)\s*\((.+)\)$")


def _format_zone_value(value: str) -> str:
    """Render a raw "Zone" cell as a letterhead subtitle.

    The body already renders the zone as ``CODE (Full Name)`` (from the
    engine's own markdown); the letterhead just swaps the separator so the
    subtitle reads as a title-block line rather than a table cell.
    """
    value = value.strip()
    m = _ZONE_PAREN_RE.match(value)
    if m:
        return f"{m.group(1)} · {m.group(2)}"
    return value


def _zone_subtitle_from_blocks(blocks: list[dict]) -> str | None:
    """Lift the letterhead zone subtitle off the report's own Zone row.

    The subtitle must never contradict the body (ABS-362) — the safest
    source of truth is whatever zone value the body itself already shows,
    whether that landed in a ``keyvals`` block (``**Zone:** ER-1``) or a
    two-column ``table`` block (a ``Field | Value`` property summary).
    """
    for block in blocks:
        if block.get("type") == "keyvals":
            for item in block.get("items", []):
                if item.get("k", "").strip().lower() == "zone" and item.get("v", "").strip():
                    return _format_zone_value(item["v"])
        elif block.get("type") == "table":
            columns = [c.strip().lower() for c in block.get("columns", [])]
            if "zone" in columns:
                idx = columns.index("zone")
                for row in block.get("rows", []):
                    cells = row.get("cells", [])
                    if idx < len(cells) and cells[idx].strip():
                        return _format_zone_value(cells[idx])
            elif len(columns) == 2:
                for row in block.get("rows", []):
                    cells = row.get("cells", [])
                    if (
                        len(cells) > 1
                        and cells[0].strip().lower() == "zone"
                        and cells[1].strip()
                    ):
                        return _format_zone_value(cells[1])
    return None


# -- Resolved zone from the engine transcript -------------------------------
# The answer markdown is the WEAKEST zone source: the engine states the zone
# free-form, so a parcel's zone can land in a table row, a keyval, or plain
# prose — and only the first two survive block parsing (ABS-362 re-test: an
# inline-prose zone left the letterhead on the hardcoded default while the
# body clearly showed the resolved DH-1). The *authoritative* source is the
# spatial resolution the engine ran to ground the answer — the same
# ``get_zone_profile`` / ``get_address_profile`` / ``search_bylaw_evidence``
# tool results the parcel pane reads (web/lib/parcel.ts). Those live in
# ``purchase.transcript_json`` (the serialized tool loop), so we mine them
# here for a deterministic zone that can never contradict the body.
_ZONING_DATASET = "halifax_zoning_boundaries"


def _tool_result_payload(content: object) -> dict | None:
    """Parse a serialized ``tool_result`` block's content into its dict.

    Each grounding tool returns ``json.dumps(compact_*(...))`` (advisor.chat
    .tools), so the content is a JSON string — or, in the block-list form,
    text blocks carrying that JSON. Anything else (a compaction summary, an
    error string) fails to parse and is skipped.
    """
    text: str | None = None
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        parts = [
            b["text"]
            for b in content
            if isinstance(b, dict)
            and b.get("type") == "text"
            and isinstance(b.get("text"), str)
        ]
        text = "".join(parts)
    if not text:
        return None
    try:
        payload = json.loads(text)
    except (ValueError, TypeError):
        return None
    return payload if isinstance(payload, dict) else None


def _zone_from_tool_payload(name: str, payload: dict) -> str | None:
    """Extract a ``CODE`` / ``CODE · Full name`` subtitle from one tool result.

    Preference is for a code *with* a human name (``get_zone_profile`` and the
    zoning-boundaries overlay carry both); ``get_address_profile`` yields only
    the code, which still beats the hardcoded default.
    """
    if name == "get_zone_profile":
        if payload.get("unknown_zone"):
            return None
        code = str(payload.get("zone") or "").strip()
        if code:
            full = str(payload.get("zone_full_name") or "").strip()
            return f"{code} · {full}" if full else code
    elif name == "get_address_profile":
        if payload.get("unresolvable"):
            return None
        code = str(payload.get("zone") or "").strip()
        if code:
            return code
    elif name == "bylaw_query":
        nested = payload.get("zone_profile")
        if isinstance(nested, dict):
            resolved = _zone_from_tool_payload("get_zone_profile", nested)
            if resolved:
                return resolved
        nested = payload.get("address_profile")
        if isinstance(nested, dict):
            resolved = _zone_from_tool_payload("get_address_profile", nested)
            if resolved:
                return resolved
    elif name == "search_bylaw_evidence":
        for match in payload.get("matches") or []:
            if not isinstance(match, dict):
                continue
            for ds in match.get("linked_datasets") or []:
                if not isinstance(ds, dict) or ds.get("name") != _ZONING_DATASET:
                    continue
                features = ds.get("feature_matches") or []
                if not features or not isinstance(features[0], dict):
                    continue
                attrs = features[0].get("canonical_attributes") or {}
                if not isinstance(attrs, dict):
                    continue
                code = str(attrs.get("zone_code") or "").strip()
                if code:
                    desc = str(attrs.get("zone_description") or "").strip()
                    return f"{code} · {desc}" if desc else code
    return None


def _zone_subtitle_from_transcript(transcript: list | None) -> str | None:
    """Lift the resolved zone off the engine's grounding tool results.

    Walks the serialized tool loop, pairing each ``tool_result`` with the
    ``tool_use`` that produced it, and returns the best zone subtitle found —
    preferring a code+name (``DH-1 · Downtown Halifax``) over a bare code. The
    tool-call *input* is a last resort: ``get_zone_profile``'s ``zone`` slot
    preserves the code even when a later compaction pass has summarised the
    result body away.
    """
    if not transcript:
        return None

    names: dict[str, str] = {}
    for message in transcript:
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if not isinstance(content, list):
            continue
        for block in content:
            if isinstance(block, dict) and block.get("type") == "tool_use":
                block_id = block.get("id")
                name = block.get("name")
                if isinstance(block_id, str) and isinstance(name, str):
                    names[block_id] = name

    code_only: str | None = None
    input_fallback: str | None = None
    for message in transcript:
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if not isinstance(content, list):
            continue
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "tool_use" and block.get("name") == "get_zone_profile":
                zone = block.get("input")
                if isinstance(zone, dict):
                    code = str(zone.get("zone") or "").strip()
                    if code and input_fallback is None:
                        input_fallback = code
            elif btype == "tool_result":
                name = names.get(block.get("tool_use_id", ""))
                if not name:
                    continue
                payload = _tool_result_payload(block.get("content"))
                if payload is None:
                    continue
                resolved = _zone_from_tool_payload(name, payload)
                if not resolved:
                    continue
                if "·" in resolved:
                    return resolved
                if code_only is None:
                    code_only = resolved
    return code_only or input_fallback


def build_report(purchase: QuestionPurchase) -> dict | None:
    """Map a captured purchase into the typed ``ReportContent`` schema.

    Returns ``None`` for any purchase without a captured answer — the
    report deliverable only exists once the engine has produced a grounded
    result. The letterhead/footer meta (issued, prepared-for, zone
    subtitle, bylaw version, verification footer) is lifted off the purchase
    record + config constants here rather than hardcoded on the client.
    """
    if purchase.status != "captured" or not purchase.answer_text:
        return None

    summary, blocks = parse_blocks(purchase.answer_text)
    verdict = _classify_verdict(purchase.answer_text, purchase.question_slug)
    ref = _ref_for(purchase)
    issued = _issued(purchase)

    meta = purchase.metadata_json or {}
    inputs = purchase.inputs_json or {}
    user = purchase.user

    prepared_for = ""
    if user is not None:
        prepared_for = (user.full_name or user.email or "").strip()

    footer = FOOTER_TEMPLATE.format(
        bylaw_version=BYLAW_VERSION, ref=ref, issued=issued or "—"
    )

    # Zone subtitle, most-authoritative source first: an explicit metadata
    # override → the zone the engine actually resolved spatially (transcript)
    # → whatever Zone the answer body itself shows → the hardcoded literal as
    # a last resort. The transcript sits above block parsing because the
    # engine states the zone free-form, so a real answer's Zone often lives in
    # inline prose that block parsing can't lift — the ABS-362 re-test failure.
    zone_subtitle = (
        meta.get("zone_subtitle")
        or _zone_subtitle_from_transcript(purchase.transcript_json)
        or _zone_subtitle_from_blocks(blocks)
        or DEFAULT_ZONE_SUBTITLE
    )

    return {
        "ref": ref,
        "report_type": _report_type(purchase),
        "address": str(inputs.get("address", "")).strip(),
        "zone_subtitle": str(zone_subtitle),
        "issued": issued,
        "prepared_for": prepared_for,
        "bylaw_version": BYLAW_VERSION,
        "price_cents": purchase.price_cents,
        "currency": purchase.currency,
        "verdict": {"status": verdict.status, "label": verdict.label},
        "summary": summary,
        "blocks": blocks,
        "footer": footer,
    }
