"""Structured report deliverable (ABS-342).

A purchased answer is the headline "report SKU" — but the engine produces
*markdown*. This module maps that engine output into the typed
``ReportContent`` schema the frontend ``ReportDocument`` template renders:
a letterhead + title + meta grid + determination band + summary + a typed
**block array** + a verification footer.

The block array is the heart of it — a small, closed set of block types
(``keyvals | uses | finding | table | flags | prose``) rendered by one
shared switch on the client, so no report type carries its own layout
code. This module is the server side of that contract: it parses the
markdown answer into those blocks and derives the report envelope
(verdict, summary, ref, and the letterhead/footer meta lifted off the
purchase record) so the client renders pure data.

Deliberately conservative: an answer whose markdown we can't confidently
decompose still yields a valid report — a single ``prose`` block carrying
the full answer — so the deliverable never regresses below today's raw
markdown. The verdict falls back to a neutral ``attention`` band when the
text carries no determination signal.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime

from advisor.billing.questions import question_for
from advisor.db.models import QuestionPurchase

# -- Lifted letterhead / footer literals (ABS-342) --------------------------
# The design handoff hardcoded these in the report chrome. They are report
# *data*, not layout, so they live here (and, where per-report, on the
# purchase record) and travel to the client in the report envelope.
BYLAW_VERSION = "HRM Regional Centre Land Use By-law — 2024 consolidation"
DEFAULT_ZONE_SUBTITLE = "Established Residential, Type 1"
FOOTER_TEMPLATE = (
    "This report was generated by ABS° and grounded in the {bylaw_version}. "
    "Reference {ref}, issued {issued}. It is a preliminary planning aid, not "
    "an official municipal determination — verify the governing provisions "
    "before relying on it."
)

# Per-question reference prefix. The ref is a human-facing report id
# ("DD-000321"); the prefix keys off the question so a customer can tell a
# due-diligence report from a compliance check at a glance.
_REF_PREFIX = {
    "permitted_use": "PU",
    "development_standards": "DS",
    "due_diligence": "DD",
    "legal_nonconforming": "NC",
    "variance_justification": "VJ",
    "other": "GR",
}


# -- Verdict classification -------------------------------------------------
# statusInfo() on the client centralizes color/tag; the server side is
# choosing WHICH status a report carries. `pass` is the only "green"
# (accent) determination; everything adverse (fail / conditional /
# attention) renders in brick.
_FAIL_SIGNALS = (
    "not permitted",
    "prohibited",
    "does not comply",
    "non-compliant",
    "fails",
    "fail",
    "violation",
)
_CONDITIONAL_SIGNALS = (
    "conditional",
    "subject to",
    "permitted with conditions",
    "requires a variance",
    "requires approval",
    "development permit required",
)
_PASS_SIGNALS = (
    "permitted as-of-right",
    "permitted as of right",
    "as-of-right",
    "is permitted",
    "complies",
    "compliant",
    "meets the",
    "conforms",
)


@dataclass(frozen=True)
class _Verdict:
    status: str
    label: str


def _classify_verdict(answer: str) -> _Verdict:
    """Derive the determination band from the answer text.

    Adverse signals win over favourable ones (a report that says "permitted
    but the rear setback fails" is not a clean pass). Falls back to a
    neutral ``attention`` band — a report with no determination keyword is
    informational, still rendered in the adverse (brick) palette so it never
    misreads as a green all-clear.
    """
    lowered = answer.lower()
    if any(sig in lowered for sig in _FAIL_SIGNALS):
        return _Verdict("fail", "Does not comply")
    if any(sig in lowered for sig in _CONDITIONAL_SIGNALS):
        return _Verdict("conditional", "Permitted with conditions")
    if any(sig in lowered for sig in _PASS_SIGNALS):
        return _Verdict("pass", "Permitted as-of-right")
    return _Verdict("attention", "Review required")


# -- Markdown → block parsing -----------------------------------------------

_HEADING_RE = re.compile(r"^\s{0,3}(#{1,6})\s+(.*\S)\s*$")
_TABLE_ROW_RE = re.compile(r"^\s*\|(.+)\|\s*$")
_TABLE_SEP_RE = re.compile(r"^\s*\|?[\s:|-]+\|?\s*$")
_BULLET_RE = re.compile(r"^\s*[-*]\s+(.*\S)\s*$")
# `**Label:** value` or `- **Label:** value`
_KEYVAL_RE = re.compile(r"^\s*(?:[-*]\s+)?\*\*(.+?)\*\*\s*:?\s*(.*)$")

_USE_STATUS = {
    "permitted": ("permitted", "pass"),
    "as-of-right": ("permitted", "pass"),
    "as of right": ("permitted", "pass"),
    "conditional": ("conditional", "conditional"),
    "prohibited": ("prohibited", "fail"),
    "not permitted": ("prohibited", "fail"),
}
_ROW_PASS = ("pass", "complies", "meets", "conforms")
_ROW_EXCEEDS = ("exceeds", "better than", "above minimum", "surpasses")
_ROW_FAIL = ("fail", "exceeds maximum", "does not comply", "over", "non-compliant")
# A table only carries per-row PASS/FAIL semantics if its header names an
# actual evaluation column (e.g. the development-standards "Result" column).
# Without this gate, `_row_status` scans every cell of every table — including
# plain field/value property-summary tables — and false-positives on
# ordinary label text (e.g. "over" inside "Governing By-law") (ABS-366).
_STATUS_COLUMN_SIGNALS = (
    "result",
    "status",
    "compliance",
    "verdict",
    "determination",
    "outcome",
    "pass/fail",
)
_FLAG_HEADINGS = ("flag", "non-conform", "concern", "warning", "risk", "issue")
_USE_HEADINGS = ("use", "permitted", "conditional")
_FINDING_HEADINGS = (
    "finding",
    "determination",
    "assessment",
    "conclusion",
    "verdict",
)


def _strip_inline(text: str) -> str:
    """Drop markdown emphasis so block payloads are plain strings."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)\*", r"\1", text)
    return text.strip()


def _row_status(cells: list[str]) -> str | None:
    """Per-row PASS / EXCEEDS / FAIL status inferred from a status-ish cell.

    The ``development_standards`` table is the driving case: each standard
    row carries a PASS or EXCEEDS verdict. We scan every cell so the status
    column can sit anywhere.
    """
    joined = " ".join(cells).lower()
    if any(sig in joined for sig in _ROW_EXCEEDS):
        return "exceeds"
    if any(sig in joined for sig in _ROW_FAIL):
        return "fail"
    if any(sig in joined for sig in _ROW_PASS):
        return "pass"
    return None


def _use_status(text: str) -> tuple[str, str] | None:
    lowered = text.lower()
    for needle, (label, status) in _USE_STATUS.items():
        if needle in lowered:
            return label, status
    return None


def _parse_table(lines: list[str]) -> dict | None:
    """Turn a contiguous markdown table into a ``table`` block."""
    rows = [ln for ln in lines if _TABLE_ROW_RE.match(ln)]
    if len(rows) < 2:
        return None

    def cells(line: str) -> list[str]:
        inner = _TABLE_ROW_RE.match(line).group(1)
        return [_strip_inline(c) for c in inner.split("|")]

    header = cells(rows[0])
    is_evaluation_table = any(
        sig in h.lower() for h in header for sig in _STATUS_COLUMN_SIGNALS
    )
    body = [r for r in rows[1:] if not _TABLE_SEP_RE.match(r)]
    out_rows = []
    for r in body:
        cvals = cells(r)
        status = _row_status(cvals) if is_evaluation_table else None
        out_rows.append({"cells": cvals, "status": status})
    if not out_rows:
        return None
    return {"type": "table", "columns": header, "rows": out_rows}


def _parse_section(heading: str | None, lines: list[str]) -> list[dict]:
    """Parse one heading section's lines into zero or more blocks."""
    body = [ln for ln in lines if ln.strip()]
    if not body:
        return []

    # A markdown table anywhere in the section becomes a table block; the
    # surrounding prose (if any) is emitted around it in order.
    if any(_TABLE_ROW_RE.match(ln) and "|" in ln for ln in body):
        table_lines = [ln for ln in body if _TABLE_ROW_RE.match(ln)]
        table = _parse_table(table_lines)
        if table is not None:
            if heading:
                table["title"] = heading
            return [table]

    bullets = [m.group(1) for ln in body if (m := _BULLET_RE.match(ln))]
    hl = (heading or "").lower()

    # Key/value pairs — "**Label:** value" lines (bulleted or not).
    keyvals = []
    for ln in body:
        m = _KEYVAL_RE.match(ln)
        if m and m.group(2).strip():
            key = _strip_inline(m.group(1)).rstrip(":").strip()
            keyvals.append({"k": key, "v": _strip_inline(m.group(2))})
    if keyvals and len(keyvals) == len([ln for ln in body if _KEYVAL_RE.match(ln)]):
        block = {"type": "keyvals", "items": keyvals}
        if heading:
            block["title"] = heading
        return [block]

    if bullets and len(bullets) == len(body):
        # A bulleted section: uses (if items carry use-status), flags (if the
        # heading signals non-conformity), else prose fallback.
        use_items = []
        for b in bullets:
            st = _use_status(b)
            if st is not None:
                label, status = st
                # Use name is the text before any dash/colon separator.
                name = re.split(r"[—:–-]", _strip_inline(b), maxsplit=1)[0].strip()
                use_items.append({"use": name or _strip_inline(b), "status": label, "note": None})
        if use_items and (any(k in hl for k in _USE_HEADINGS) or len(use_items) == len(bullets)):
            block = {"type": "uses", "items": use_items}
            if heading:
                block["title"] = heading
            return [block]

        if any(k in hl for k in _FLAG_HEADINGS):
            flag_items = []
            for b in bullets:
                st = _use_status(b)
                status = st[1] if st else "attention"
                flag_items.append({"status": status, "text": _strip_inline(b)})
            block = {"type": "flags", "items": flag_items}
            if heading:
                block["title"] = heading
            return [block]

    # A determination-style section (no bullets/table/keyvals) becomes a
    # highlighted `finding` callout carrying the section's own verdict.
    text = "\n".join(_strip_inline(ln) for ln in body)
    if any(k in hl for k in _FINDING_HEADINGS):
        verdict = _classify_verdict(text)
        return [
            {
                "type": "finding",
                "title": heading,
                "status": verdict.status,
                "body": text,
            }
        ]

    # Everything else is prose.
    block = {"type": "prose", "text": text}
    if heading:
        block["title"] = heading
    return [block]


def parse_blocks(answer: str) -> tuple[str, list[dict]]:
    """Split a markdown answer into ``(summary, blocks)``.

    The summary is the lead — the text before the first heading (or the
    first paragraph if the answer is heading-less). Everything after is
    decomposed section-by-section into typed blocks. A heading-less,
    structure-less answer degrades to one prose block so the report is
    always valid.
    """
    lines = answer.replace("\r\n", "\n").split("\n")

    # Lead paragraph → summary (until the first heading or blank-line break).
    summary_lines: list[str] = []
    idx = 0
    while idx < len(lines):
        if _HEADING_RE.match(lines[idx]):
            break
        if not lines[idx].strip() and summary_lines:
            break
        if lines[idx].strip():
            summary_lines.append(lines[idx])
        idx += 1
    summary = _strip_inline(" ".join(summary_lines)).strip()

    # Sections keyed by heading.
    blocks: list[dict] = []
    heading: str | None = None
    buf: list[str] = []

    def flush() -> None:
        nonlocal buf, heading
        blocks.extend(_parse_section(heading, buf))
        buf = []

    for ln in lines[idx:]:
        m = _HEADING_RE.match(ln)
        if m:
            flush()
            heading = _strip_inline(m.group(2))
        else:
            buf.append(ln)
    flush()

    if not summary and not blocks:
        summary = _strip_inline(answer).strip()
    if not blocks and answer.strip():
        # No sections parsed — carry the whole answer as prose so the
        # deliverable never falls below raw markdown.
        remainder = answer.strip()
        if remainder and remainder != summary:
            blocks.append({"type": "prose", "text": _strip_inline(remainder)})
    return summary, blocks


# -- Envelope builder -------------------------------------------------------


def _ref_for(purchase: QuestionPurchase) -> str:
    prefix = _REF_PREFIX.get(purchase.question_slug, "GR")
    return f"{prefix}-{purchase.id:06d}"


def _report_type(purchase: QuestionPurchase) -> str:
    try:
        return question_for(purchase.question_slug).display_name
    except KeyError:
        return "Bylaw report"


def _issued(purchase: QuestionPurchase) -> str:
    dt = purchase.settled_at or purchase.answered_at
    if isinstance(dt, datetime):
        return dt.date().isoformat()
    return ""


def build_report(purchase: QuestionPurchase) -> dict | None:
    """Map a captured purchase into the typed ``ReportContent`` schema.

    Returns ``None`` for any purchase without a captured answer — the
    report deliverable only exists once the engine has produced a grounded
    result. The letterhead/footer meta (issued, prepared-for, zone
    subtitle, bylaw version, verification footer) is lifted off the purchase
    record + config constants here rather than hardcoded on the client.
    """
    if purchase.status != "captured" or not purchase.answer_text:
        return None

    summary, blocks = parse_blocks(purchase.answer_text)
    verdict = _classify_verdict(purchase.answer_text)
    ref = _ref_for(purchase)
    issued = _issued(purchase)

    meta = purchase.metadata_json or {}
    inputs = purchase.inputs_json or {}
    user = purchase.user

    prepared_for = ""
    if user is not None:
        prepared_for = (user.full_name or user.email or "").strip()

    footer = FOOTER_TEMPLATE.format(
        bylaw_version=BYLAW_VERSION, ref=ref, issued=issued or "—"
    )

    return {
        "ref": ref,
        "report_type": _report_type(purchase),
        "address": str(inputs.get("address", "")).strip(),
        "zone_subtitle": str(meta.get("zone_subtitle") or DEFAULT_ZONE_SUBTITLE),
        "issued": issued,
        "prepared_for": prepared_for,
        "bylaw_version": BYLAW_VERSION,
        "price_cents": purchase.price_cents,
        "currency": purchase.currency,
        "verdict": {"status": verdict.status, "label": verdict.label},
        "summary": summary,
        "blocks": blocks,
        "footer": footer,
    }
