// Functional: ABS-346 — document-level report export (Export PDF + Share).
//
// The report PDF is the PRIMARY deliverable. This spec asserts the reconciled
// hierarchy the ticket calls for:
//   - the report view's "Export PDF" opens the dedicated report print surface
//     (/app/print?report_id=N) which renders the ReportDocument (letterhead →
//     findings → verification footer) — NOT the chat transcript;
//   - the report view exposes Share;
//   - the right-pane sources export is demoted to the secondary "sources
//     appendix" when a report is the primary deliverable.
//
// Same network-boundary stubbing as the ABS-342 / ABS-344 answer specs: only
// the purchase-detail proxy is faked; the shared /app shell drives for real.

import { expect, test } from "../fixtures/test-env";
import type { BrowserContext, Route } from "@playwright/test";

type Report = Record<string, unknown>;

function report(): Report {
  return {
    ref: "DD-000346",
    report_type: "Zoning due-diligence summary",
    address: "1234 Elm Street",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-03",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 19900,
    currency: "CAD",
    verdict: { status: "conditional", label: "Permitted with conditions" },
    summary: "A preliminary zoning due-diligence summary for 1234 Elm Street.",
    blocks: [
      {
        type: "finding",
        status: "conditional",
        title: "Rear-yard setback",
        body: "The existing structure sits within the minimum rear-yard setback.",
      },
    ],
    footer: "This report was generated by ABS° · reference DD-000346.",
  };
}

type Purchase = {
  id: number;
  question_slug: string;
  status: string;
  price_cents: number;
  currency: string;
  answer: string | null;
  report: Report | null;
  failure_reason: string | null;
  refinement_count: number;
  refinements_remaining: number;
  window_expires_at: string | null;
};

function purchase(overrides: Partial<Purchase> = {}): Purchase {
  return {
    id: 346,
    question_slug: "due_diligence",
    status: "captured",
    price_cents: 19900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: report(),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

// Context-level route so the interception also covers the export popup (a
// separate Page). Handles both the GET detail and the POST /answer auto-run.
async function stubPurchaseApi(
  context: BrowserContext,
  get: () => unknown,
) {
  await context.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route: Route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(get()),
      }),
  );
}

test.describe("report document export (ABS-346)", () => {
  test("Export PDF opens the ReportDocument print surface, not the transcript", async ({
    page,
    context,
  }) => {
    await stubPurchaseApi(context, () => purchase());
    await page.goto("/app?report_id=346");

    // In report view the toolbar exposes both Share and Export PDF.
    await expect(page.getByTestId("report-document")).toBeVisible();
    await expect(page.getByTestId("case-toolbar-share")).toBeVisible();
    const exportBtn = page.getByTestId("case-toolbar-export");
    await expect(exportBtn).toBeVisible();

    // Clicking Export PDF opens the dedicated report print surface.
    const [popup] = await Promise.all([
      page.waitForEvent("popup"),
      exportBtn.click(),
    ]);
    await expect(popup).toHaveURL(/\/app\/print\?report_id=346/);

    // The print surface renders the structured ReportDocument — letterhead
    // (report-type + ref), findings, and the verification footer …
    await expect(popup.getByTestId("report-print")).toBeVisible();
    await expect(popup.getByTestId("report-document")).toBeVisible();
    await expect(popup.getByTestId("report-type")).toContainText(
      /due-diligence/i,
    );
    await expect(popup.getByTestId("report-ref")).toHaveText("DD-000346");
    await expect(popup.getByTestId("report-address")).toHaveText(
      "1234 Elm Street",
    );
    await expect(popup.getByTestId("block-finding")).toContainText(
      /rear-yard setback/i,
    );
    await expect(popup.getByTestId("report-footer")).toContainText(
      "DD-000346",
    );

    // … and NOT the chat-session transcript surface.
    await expect(popup.getByTestId("transcript-print")).toHaveCount(0);
  });

  test("report print surface loads directly from a report_id", async ({
    page,
    context,
  }) => {
    await stubPurchaseApi(context, () => purchase());
    await page.goto("/app/print?report_id=346");

    await expect(page.getByTestId("report-document")).toBeVisible();
    await expect(page.getByTestId("report-address")).toHaveText(
      "1234 Elm Street",
    );
    await expect(page.getByTestId("report-verdict")).toContainText(
      "Permitted with conditions",
    );
  });

  test("right-pane sources export is demoted to the appendix when report-backed", async ({
    page,
    context,
  }) => {
    await stubPurchaseApi(context, () => purchase());
    await page.goto("/app?report_id=346");

    await expect(page.getByTestId("report-document")).toBeVisible();

    // The parcel pane's export reads as the secondary sources appendix — the
    // report (toolbar Export PDF) is the primary deliverable.
    const parcelExport = page.getByTestId("parcel-export");
    await expect(parcelExport).toHaveText(/Export sources \(appendix\)/i);
  });
});
