// Functional: ABS-353 — stale ``report_id`` in the URL kept the previous
// report face mounted after switching to a conversation-only case.
//
// selectSession()'s URL sync (chat-shell.tsx) only ever set/deleted
// ``case_id``/``case_number`` — it never deleted ``report_id``. So opening a
// report case (`/app?report_id=N`), then clicking an old conversation-only
// case in the sidebar, produced `/app?report_id=N&case_id=M`: the center
// pane kept rendering report N's face (isReportBacked derives from
// ``reportIdFromUrl``) instead of the clicked conversation, and the
// Report·Conversation toggle stayed around, mislabeled for the wrong case.
//
// The fix adds `params.delete("report_id")` alongside the existing
// `case_number` delete. This spec drives the real /app workspace: a report
// opened via ?report_id= (purchase-detail proxy stubbed, same pattern as the
// ABS-344/352 specs), then a REAL conversation-only case+session (seeded via
// openCaseViaApi + ?first_message=, same pattern as ABS-182) selected from
// the sidebar. It asserts the report face fully unmounts, the URL drops
// report_id, and no POST /answer fires as a side effect of the switch.

import { expect, openCaseViaApi, test } from "../fixtures/test-env";
import type { Route } from "@playwright/test";

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

const REPORT_ID = 3530;

function capturedPurchase() {
  return {
    id: REPORT_ID,
    question_slug: "due_diligence",
    status: "captured",
    price_cents: 19900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: {
      ref: "DD-003530",
      report_type: "Zoning due-diligence summary",
      address: "3530 Bramble Court",
      zone_subtitle: "Established Residential, Type 1",
      issued: "2026-07-04",
      prepared_for: "Jordan Buyer",
      bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
      price_cents: 19900,
      currency: "CAD",
      verdict: { status: "conditional", label: "Permitted with conditions" },
      summary: "A preliminary zoning due-diligence summary for 3530 Bramble Court.",
      blocks: [],
      footer: "This report was generated by ABS° · reference DD-003530.",
    },
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
  };
}

test("switching from a report case to a conversation-only case via the sidebar clears report_id and unmounts the report face (ABS-353)", async ({
  page,
}) => {
  const ts = Date.now();
  const firstMessage = "What is the minimum front yard setback?";

  // Seed a REAL conversation-only case + session (no report) up front, same
  // as ABS-182 — this is the case we'll click on from the sidebar later.
  const anchorLabel = `9353 Convo Lane ${ts}, Halifax`;
  const { caseId: convoCaseId } = await openCaseViaApi({ anchorLabel });
  await page.goto(
    `/app?case_id=${convoCaseId}&first_message=${encodeURIComponent(firstMessage)}`,
  );
  await expect(page.getByTestId("chat-thread")).toContainText(
    /Based on the bylaw evidence/i,
    { timeout: 15_000 },
  );

  // Stub the report's purchase-detail proxy. The report is already
  // `captured`, so the initial load never fires POST /answer — any POST we
  // observe from here on must come from the (buggy) switch, not a normal
  // generation run.
  let postAnswerCount = 0;
  await page.route(
    new RegExp(`/api/billing/questions/purchases/${REPORT_ID}(/(answer|refine))?$`),
    (route) => {
      const url = route.request().url();
      const method = route.request().method();
      if (method === "POST" && url.endsWith("/answer")) {
        postAnswerCount += 1;
      }
      return json(route, capturedPurchase());
    },
  );

  // Open the report case — center pane shows the report face + toolbar.
  await page.goto(`/app?report_id=${REPORT_ID}`);
  await expect(page.getByTestId("case-toolbar")).toBeVisible();
  await expect(page.getByTestId("report-document")).toBeVisible();
  await expect(page.getByTestId("report-address")).toHaveText(
    "3530 Bramble Court",
  );
  await expect(page).toHaveURL(new RegExp(`report_id=${REPORT_ID}`));

  // Click the real conversation-only case in the sidebar (the sessions list
  // hits the real backend — no stubbing needed, matching ABS-182).
  const sidebar = page.locator("aside").first();
  const convoRow = sidebar.getByRole("button", {
    name: new RegExp(escapeRegExp(`Convo Lane ${ts}`), "i"),
  });
  await expect(convoRow).toBeVisible({ timeout: 8_000 });
  await convoRow.click();

  // URL must drop report_id and carry the conversation's case_id.
  await expect(page).toHaveURL(new RegExp(`case_id=${convoCaseId}`), {
    timeout: 5_000,
  });
  expect(page.url()).not.toMatch(/report_id=/);

  // The report face is fully gone — no toolbar, no report document — and
  // the chat thread (this case's actual conversation) renders instead.
  await expect(page.getByTestId("case-toolbar")).toHaveCount(0);
  await expect(page.getByTestId("report-document")).toHaveCount(0);
  await expect(page.getByTestId("chat-thread")).toContainText(
    /Based on the bylaw evidence/i,
    { timeout: 10_000 },
  );
  await expect(page.getByTestId("workspace-label")).toContainText(
    "CONVERSATION",
  );

  // The switch itself must not have triggered any report generation.
  expect(postAnswerCount).toBe(0);
});

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
