// Functional: ABS-342 structured report deliverable (ReportDocument).
//
// A `captured` purchase renders through one shared ReportDocument template
// in a fixed section order (letterhead → title → meta grid → determination
// band → summary → typed body blocks → verification footer), driven by a
// typed block array. This spec drives the real /app/answers view and stubs
// the purchase proxy at the network boundary (same pattern as the ABS-321
// answer-view spec) with a structured `report` payload, and asserts:
//   - due_diligence exercises keyvals / uses / finding / flags / prose;
//   - development_standards exercises the `table` block with per-row
//     PASS / EXCEEDS status;
//   - the letterhead/footer meta lifted onto the report record renders
//     (issued, prepared-for, zone subtitle, bylaw version, price, footer).

import { expect, test } from "../fixtures/test-env";
import type { Page, Route } from "@playwright/test";

type Report = Record<string, unknown>;

function dueDiligenceReport(): Report {
  return {
    ref: "DD-000342",
    report_type: "Zoning due-diligence summary",
    address: "1234 Elm Street",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-03",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 19900,
    currency: "CAD",
    verdict: { status: "conditional", label: "Permitted with conditions" },
    summary:
      "A preliminary zoning due-diligence summary for 1234 Elm Street.",
    blocks: [
      {
        type: "keyvals",
        title: "Zoning",
        items: [
          { k: "Zone", v: "ER-1" },
          { k: "Overlay", v: "Heritage Conservation" },
        ],
      },
      {
        type: "uses",
        title: "Permitted Uses",
        items: [
          { use: "Single detached dwelling", status: "permitted", note: null },
          { use: "Corner store", status: "conditional", note: "site plan" },
          { use: "Light industrial", status: "prohibited", note: null },
        ],
      },
      {
        type: "finding",
        status: "conditional",
        title: "Rear-yard setback",
        body: "The existing structure sits within the minimum rear-yard setback.",
      },
      {
        type: "flags",
        title: "Non-conformity Flags",
        items: [
          { status: "attention", text: "Lot coverage close to the maximum." },
          { status: "fail", text: "Rear setback below the minimum." },
        ],
      },
      {
        type: "prose",
        title: "Notes",
        text: "This is a preliminary aid, not a substitute for a full memo.",
      },
    ],
    footer:
      "This report was generated by ABS° and grounded in the HRM Regional " +
      "Centre Land Use By-law — 2024 consolidation. Reference DD-000342, " +
      "issued 2026-07-03.",
  };
}

function developmentStandardsReport(): Report {
  return {
    ref: "DS-000343",
    report_type: "Development-standards compliance check",
    address: "50 Quarry Road",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-03",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 14900,
    currency: "CAD",
    verdict: { status: "pass", label: "Complies with as-of-right standards" },
    summary: "The proposal complies with the zone's as-of-right standards.",
    blocks: [
      {
        type: "table",
        title: "Development Standards",
        columns: ["Standard", "Required", "Proposed"],
        rows: [
          { cells: ["Height", "11 m max", "10.5 m"], status: "pass" },
          { cells: ["Front setback", "6 m min", "7.5 m"], status: "exceeds" },
          { cells: ["Lot coverage", "40% max", "35%"], status: "pass" },
        ],
      },
    ],
  };
}

// ABS-366 repro shape: the backend now classifies a plain field/value
// table (no evaluation/standards column in its header) with `status: null`
// on every row — this is what a fixed `build_report` emits for a
// Property Summary section that happens to be authored as a markdown
// table. The "Governing By-law" row has no pass/fail semantics and must
// not render a status pill.
function propertySummaryReport(): Report {
  return {
    ref: "PU-000366",
    report_type: "Permitted-use determination",
    address: "5184 Morris St",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-03",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 9900,
    currency: "CAD",
    verdict: { status: "pass", label: "Permitted as-of-right" },
    summary: "The proposed use is permitted as-of-right at 5184 Morris St.",
    blocks: [
      {
        type: "table",
        title: "Property Summary",
        columns: ["Field", "Value"],
        rows: [
          { cells: ["Zone", "ER-1"], status: null },
          {
            cells: ["Governing By-law", "Regional Centre Land Use By-Law"],
            status: null,
          },
        ],
      },
    ],
  };
}

// ABS-373 repro shape: a development-standards evaluation table (its header
// names a "Result" column, so per-row status derivation is ON) whose Lot
// Coverage and FAR rows are N/A / not-regulated. The fixed `build_report`
// emits `status: null` on those rows — even though "Lot Coverage" contains
// the substring "over" (a FAIL signal) — while a genuinely failing row keeps
// its "fail" status. A paid report must never show a FAIL pill next to a
// "not regulated / no maximum" verdict.
function naVerdictReport(): Report {
  return {
    ref: "DS-000373",
    report_type: "Development-standards compliance check",
    address: "1250 Robie St",
    zone_subtitle: "Institutional (INS)",
    issued: "2026-07-09",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 14900,
    currency: "CAD",
    verdict: { status: "pass", label: "Complies with as-of-right standards" },
    summary: "The proposal complies with the zone's as-of-right standards.",
    blocks: [
      {
        type: "table",
        title: "Built-form standards",
        columns: ["Standard", "Required", "Proposed", "Result"],
        rows: [
          {
            cells: ["Lot Coverage", "—", "42%", "N/A — no maximum in INS zone"],
            status: null,
          },
          { cells: ["FAR", "—", "1.4", "N/A (no limit)"], status: null },
          { cells: ["Height", "20 m max", "18 m", "PASS"], status: "pass" },
          {
            cells: ["Rear setback", "8 m min", "4 m", "FAIL"],
            status: "fail",
          },
        ],
      },
      {
        type: "table",
        title: "Summary",
        columns: ["Standard", "Result"],
        rows: [
          { cells: ["Lot Coverage", "N/A (no limit)"], status: null },
          { cells: ["FAR", "N/A (no limit)"], status: null },
        ],
      },
    ],
  };
}

type Purchase = {
  id: number;
  question_slug: string;
  status: string;
  price_cents: number;
  currency: string;
  answer: string | null;
  report: Report | null;
  failure_reason: string | null;
  refinement_count: number;
  refinements_remaining: number;
  window_expires_at: string | null;
};

function purchase(overrides: Partial<Purchase> = {}): Purchase {
  return {
    id: 342,
    question_slug: "due_diligence",
    status: "captured",
    price_cents: 19900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: dueDiligenceReport(),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

async function stubPurchase(page: Page, get: () => unknown) {
  await page.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route) => json(route, get()),
  );
}

test.describe("structured report deliverable (ABS-342)", () => {
  test("due_diligence renders the full ReportDocument chrome + all block types", async ({
    page,
  }) => {
    await stubPurchase(page, () => purchase());
    await page.goto("/app/answers/342");

    const doc = page.getByTestId("report-document");
    await expect(doc).toBeVisible();

    // Letterhead — report-type + ref.
    await expect(page.getByTestId("report-type")).toContainText(
      /due-diligence/i,
    );
    await expect(page.getByTestId("report-ref")).toHaveText("DD-000342");

    // Title block — address + zone.
    await expect(page.getByTestId("report-address")).toHaveText(
      "1234 Elm Street",
    );
    await expect(page.getByTestId("report-zone")).toHaveText(
      "Established Residential, Type 1",
    );

    // Meta grid — issued · prepared-for · bylaw version · price paid.
    const meta = page.getByTestId("report-meta");
    await expect(meta).toContainText("2026-07-03");
    await expect(meta).toContainText("Jordan Buyer");
    await expect(meta).toContainText(/2024 consolidation/);
    await expect(meta).toContainText("$199.00 CAD");

    // Determination band — status chip + verdict headline.
    await expect(page.getByTestId("report-verdict-chip")).toHaveText(
      "CONDITIONAL",
    );
    await expect(page.getByTestId("report-verdict")).toContainText(
      "Permitted with conditions",
    );

    // Summary.
    await expect(page.getByTestId("report-summary")).toContainText(
      /preliminary zoning due-diligence/i,
    );

    // All five body-block renderers this report exercises.
    await expect(page.getByTestId("block-keyvals")).toContainText("ER-1");
    await expect(page.getByTestId("block-uses")).toContainText(
      "Single detached dwelling",
    );
    await expect(page.getByTestId("block-finding")).toContainText(
      /rear-yard setback/i,
    );
    await expect(page.getByTestId("block-flags")).toContainText(
      /rear setback below the minimum/i,
    );
    await expect(page.getByTestId("block-prose")).toContainText(
      /preliminary aid/i,
    );

    // Verification footer.
    await expect(page.getByTestId("report-footer")).toContainText(
      "DD-000342",
    );

    // The refinement composer still lives below the report.
    await expect(page.getByTestId("refine-remaining")).toContainText(
      /3 FOLLOW-UPS LEFT/i,
    );
  });

  test("development_standards renders the table block with per-row PASS/EXCEEDS", async ({
    page,
  }) => {
    await stubPurchase(page, () =>
      purchase({
        id: 343,
        question_slug: "development_standards",
        price_cents: 14900,
        report: developmentStandardsReport(),
      }),
    );
    await page.goto("/app/answers/343");

    await expect(page.getByTestId("report-document")).toBeVisible();

    const table = page.getByTestId("block-table");
    await expect(table).toBeVisible();
    await expect(table).toContainText("Height");
    await expect(table).toContainText("Front setback");

    // Per-row status tags: the table exercises both PASS and EXCEEDS.
    const statuses = page.getByTestId("row-status");
    await expect(statuses).toHaveCount(3);
    await expect(statuses.filter({ hasText: "PASS" })).toHaveCount(2);
    await expect(statuses.filter({ hasText: "EXCEEDS" })).toHaveCount(1);

    // A clean compliance report carries the favourable (accent) verdict.
    await expect(page.getByTestId("report-verdict-chip")).toHaveText("PASS");
  });

  test("ABS-366: a property-summary table with no evaluation column renders no stray status pill", async ({
    page,
  }) => {
    await stubPurchase(page, () =>
      purchase({
        id: 366,
        question_slug: "permitted_use",
        price_cents: 9900,
        report: propertySummaryReport(),
      }),
    );
    await page.goto("/app/answers/366");

    const table = page.getByTestId("block-table");
    await expect(table).toBeVisible();
    await expect(table).toContainText("Governing By-law");
    await expect(table).toContainText("Regional Centre Land Use By-Law");

    // Non-status rows (Zone, Governing By-law) must never carry a pill.
    await expect(page.getByTestId("row-status")).toHaveCount(0);
    await expect(table).not.toContainText("FAIL");
  });

  test("ABS-373: N/A / not-regulated rows in an evaluation table render no pill, genuine FAIL stays", async ({
    page,
  }) => {
    await stubPurchase(page, () =>
      purchase({
        id: 373,
        question_slug: "development_standards",
        price_cents: 14900,
        report: naVerdictReport(),
      }),
    );
    await page.goto("/app/answers/373");

    await expect(page.getByTestId("report-document")).toBeVisible();

    // Both the built-form table and the summary table carry Lot Coverage /
    // FAR rows whose verdict is N/A. Neither may render a status pill — even
    // though "Lot Coverage" contains the substring "over".
    const rows = page.getByTestId("table-row");
    const lotCoverageRows = rows.filter({ hasText: "Lot Coverage" });
    await expect(lotCoverageRows).toHaveCount(2);
    for (let i = 0; i < 2; i++) {
      await expect(
        lotCoverageRows.nth(i).getByTestId("row-status"),
      ).toHaveCount(0);
      await expect(lotCoverageRows.nth(i)).not.toContainText("FAIL");
    }

    // The FAR rows (same N/A verdict) are likewise pill-free.
    const farRows = rows.filter({ hasText: "FAR" });
    await expect(farRows).toHaveCount(2);
    for (let i = 0; i < 2; i++) {
      await expect(farRows.nth(i).getByTestId("row-status")).toHaveCount(0);
    }

    // A genuinely failing row still shows its FAIL pill — the fix is targeted,
    // not a blanket suppression of all row status.
    const failRow = rows.filter({ hasText: "Rear setback" });
    await expect(failRow.getByTestId("row-status")).toHaveText("FAIL");

    // Exactly two pills total across the report: the PASS (Height) and the
    // FAIL (Rear setback) rows — the four N/A rows contribute none.
    await expect(page.getByTestId("row-status")).toHaveCount(2);
  });

  test("falls back to raw markdown when no structured report is present", async ({
    page,
  }) => {
    await stubPurchase(page, () =>
      purchase({
        report: null,
        answer: "Based on the bylaw evidence, the use is permitted.",
      }),
    );
    await page.goto("/app/answers/342");

    await expect(page.getByTestId("report-document")).toHaveCount(0);
    await expect(page.getByTestId("answer-body")).toContainText(
      /Based on the bylaw evidence/i,
    );
  });
});
