// Functional: ABS-361 — switching reports in the sidebar showed stale /
// loading content in the center pane.
//
// The /app route is a `force-dynamic` server component (page.tsx runs a
// terms-acceptance GET on every render). The sidebar switched reports with
// `router.push('/app?report_id=N')` — a soft client nav that re-runs that
// server round-trip BEFORE `useSearchParams` (and thus the keyed
// <AnswerView>) sees the new id. So clicking a different report:
//   - kept the PREVIOUS report's document in the center pane for the ~2s
//     round-trip (stale), then flipped; and
//   - sometimes coalesced into a no-op (URL didn't change on the first click).
//
// The fix switches report navigation to `window.history.pushState`, which
// integrates with the Next router and updates `useSearchParams` synchronously
// on the client with no server round-trip — so the center pane swaps to the
// clicked report immediately (a brief AnswerView loading spinner at most,
// never the previous report's content). It also highlights the clicked report
// row instantly (`activeReportId` → `data-active`).
//
// This spec drives the real /app workspace + sidebar (not page.goto per
// report, which would mask the bug by remounting the whole page) and stubs
// only the purchase proxy + sidebar list endpoints at the network boundary,
// matching the ABS-344/352/353 specs.

import { expect, test } from "../fixtures/test-env";
import type { Page, Route } from "@playwright/test";

type Report = Record<string, unknown>;

function reportDoc(id: number, address: string): Report {
  return {
    ref: `DD-00${id}`,
    report_type: "Zoning due-diligence summary",
    address,
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-06",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 19900,
    currency: "CAD",
    verdict: { status: "conditional", label: "Permitted with conditions" },
    summary: `A preliminary zoning due-diligence summary for ${address}.`,
    blocks: [],
    footer: `This report was generated by ABS° · reference DD-00${id}.`,
  };
}

function purchase(id: number, address: string, overrides: Report = {}): Report {
  return {
    id,
    question_slug: "due_diligence",
    status: "captured",
    price_cents: 19900,
    currency: "CAD",
    answer: `Grounded answer for report ${id}.`,
    report: reportDoc(id, address),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

const REPORT_A = {
  id: 6101,
  question_slug: "due_diligence",
  title: "Due diligence report",
  status: "captured",
  address: "1967 Woodlawn Terrace",
  zone: "R-1",
  answer_ready: true,
  updated_at: "2026-07-06T09:00:00Z",
};

const REPORT_B = {
  id: 6102,
  question_slug: "permitted_use",
  title: "Permitted-use check",
  status: "captured",
  address: "42 Spring Garden Road",
  zone: "COR",
  answer_ready: true,
  updated_at: "2026-07-06T09:05:00Z",
};

async function stubSidebar(page: Page, reports: unknown[]) {
  await page.route(/\/api\/chat\/sessions(\?.*)?$/, (route) =>
    json(route, { sessions: [] }),
  );
  await page.route(/\/api\/billing\/questions\/purchases$/, (route) =>
    json(route, { reports }),
  );
}

test.describe("switching reports in the sidebar (ABS-361)", () => {
  test("a single click swaps the center pane to the clicked report — no stale content, no recharge", async ({
    page,
  }) => {
    // Both reports are already `captured`, so GETs render straight away and no
    // POST /answer should ever fire. A POST here would mean a spurious
    // regenerate/recharge on switch — the exact thing the ticket rules out.
    let postAnswerCount = 0;
    await page.route(
      /\/api\/billing\/questions\/purchases\/(\d+)(\/(answer|refine))?$/,
      (route) => {
        const url = route.request().url();
        const method = route.request().method();
        const id = Number(url.match(/purchases\/(\d+)/)?.[1]);
        if (method === "POST" && url.endsWith("/answer")) {
          postAnswerCount += 1;
        }
        const address =
          id === REPORT_A.id ? REPORT_A.address : REPORT_B.address;
        return json(route, purchase(id, address));
      },
    );
    await stubSidebar(page, [REPORT_A, REPORT_B]);

    await page.goto("/app");
    const sidebar = page.locator("aside").first();
    const rowA = sidebar.getByTestId("case-row").filter({
      hasText: REPORT_A.address,
    });
    const rowB = sidebar.getByTestId("case-row").filter({
      hasText: REPORT_B.address,
    });

    // Open report A.
    await rowA.click();
    await expect(page).toHaveURL(/report_id=6101/);
    await expect(page.getByTestId("report-address")).toHaveText(
      REPORT_A.address,
    );
    await expect(rowA).toHaveAttribute("data-active", "true");

    // A single click on report B must switch the whole workspace: URL, the
    // active row, and — critically — the center document, with no lingering
    // report-A content.
    await rowB.click();
    await expect(page).toHaveURL(/report_id=6102/);
    await expect(page.getByTestId("report-address")).toHaveText(
      REPORT_B.address,
    );
    // Exactly one report document renders, and it's report B — report A's
    // document is gone (not stale behind the new URL). Scoped to the center
    // canvas because the sidebar still lists report A's address.
    await expect(page.getByTestId("report-document")).toHaveCount(1);
    await expect(
      page.getByTestId("report-canvas").getByText(REPORT_A.address),
    ).toHaveCount(0);
    // The clicked row is active; the previous row isn't.
    await expect(rowB).toHaveAttribute("data-active", "true");
    await expect(rowA).toHaveAttribute("data-active", "false");

    // Switching never regenerated or re-charged either report.
    expect(postAnswerCount).toBe(0);
  });

  test("while the clicked report loads, the center shows a spinner — never the previous report", async ({
    page,
  }) => {
    // Gate report B's GET so the switch's intermediate state is observable.
    // With the bug the previous (report-A) document stayed mounted through the
    // soft-nav server round-trip; with the fix <AnswerView> remounts
    // synchronously and shows its loading indicator while B's GET is in flight.
    let releaseB = () => {};
    const bGate = new Promise<void>((resolve) => {
      releaseB = resolve;
    });

    await page.route(
      /\/api\/billing\/questions\/purchases\/(\d+)(\/(answer|refine))?$/,
      async (route) => {
        const url = route.request().url();
        const id = Number(url.match(/purchases\/(\d+)/)?.[1]);
        if (id === REPORT_B.id) {
          await bGate; // hold B's fetch open
          return json(route, purchase(id, REPORT_B.address));
        }
        return json(route, purchase(id, REPORT_A.address));
      },
    );
    await stubSidebar(page, [REPORT_A, REPORT_B]);

    await page.goto("/app");
    const sidebar = page.locator("aside").first();
    await sidebar
      .getByTestId("case-row")
      .filter({ hasText: REPORT_A.address })
      .click();
    await expect(page.getByTestId("report-address")).toHaveText(
      REPORT_A.address,
    );

    // Click B — its GET is gated, so the pane must show the loading indicator,
    // and report A's document must already be gone (no stale carry-over).
    await sidebar
      .getByTestId("case-row")
      .filter({ hasText: REPORT_B.address })
      .click();
    await expect(page).toHaveURL(/report_id=6102/);
    await expect(page.getByTestId("answer-status")).toBeVisible();
    // No report document is mounted while B loads — report A's document
    // unmounted synchronously rather than lingering as stale content.
    await expect(page.getByTestId("report-document")).toHaveCount(0);

    // Release B — its real document renders.
    releaseB();
    await expect(page.getByTestId("report-address")).toHaveText(
      REPORT_B.address,
      { timeout: 10_000 },
    );
  });
});
