// Functional: ABS-359 — the report Summary must be a clean lead paragraph,
// never the agent's planning monologue or a stray horizontal rule.
//
// The bug: the engine's markdown opens with the agent "thinking out loud"
// ("I have gathered the key provisions … Let me compile the findings:")
// fenced off from the report by a `---` horizontal rule, and sprinkles bare
// `---` dividers between sections. The old parser lifted that monologue into
// the Summary block and let the literal `---` leak into prose — chain-of-
// thought on a paid, exportable deliverable.
//
// The fix lives in the server-side parser (advisor.billing.report.parse_blocks):
// it strips the fenced monologue + every stray rule and derives a clean lead.
// The parser logic is pinned by unit tests in tests/advisor/billing/
// test_report.py. This spec drives the real /app/answers view (same
// stub-at-the-network-boundary pattern as the ABS-342/362/365/366 report
// specs) with the *cleaned* report the fixed backend now emits, and guards the
// rendered contract: the Summary shows the clean lead, and no monologue text
// or `---` ever surfaces anywhere in the document.

import { expect, test } from "../fixtures/test-env";
import type { Page, Route } from "@playwright/test";

type Report = Record<string, unknown>;

// The report a fixed build_report emits for the 5686 Spring Garden Rd
// variance package: the monologue + fencing rule stripped, the inter-section
// `---` gone, a clean lead promoted into the summary.
function varianceReport(): Report {
  return {
    ref: "VJ-000359",
    report_type: "Variance justification package",
    address: "5686 Spring Garden Rd",
    zone_subtitle: "DH-1 · Downtown Halifax - 1",
    issued: "2026-07-07",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 29900,
    currency: "CAD",
    verdict: {
      status: "conditional",
      label: "Supportable with conditions",
    },
    summary:
      "The requested rear-yard variance is supportable on all three statutory tests.",
    blocks: [
      {
        type: "finding",
        status: "conditional",
        title: "Statutory Test 1 — Minor in nature",
        body: "The 0.4 m encroachment is minor relative to the required setback.",
      },
      {
        type: "prose",
        title: "Statutory Test 2 — Intent of the by-law",
        text: "The variance is consistent with the intent of the DH-1 zone.",
      },
    ],
    footer:
      "This report was generated by ABS° and grounded in the HRM Regional " +
      "Centre Land Use By-law — 2024 consolidation. Reference VJ-000359, " +
      "issued 2026-07-07.",
  };
}

type Purchase = {
  id: number;
  question_slug: string;
  status: string;
  price_cents: number;
  currency: string;
  answer: string | null;
  report: Report | null;
  failure_reason: string | null;
  refinement_count: number;
  refinements_remaining: number;
  window_expires_at: string | null;
};

function purchase(overrides: Partial<Purchase> = {}): Purchase {
  return {
    id: 359,
    question_slug: "variance_justification",
    status: "captured",
    price_cents: 29900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: varianceReport(),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

async function stubPurchase(page: Page, get: () => unknown) {
  await page.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route) => json(route, get()),
  );
}

test.describe("report summary is a clean lead, not agent monologue (ABS-359)", () => {
  test("summary shows the clean lead; no monologue or stray rule leaks into the document", async ({
    page,
  }) => {
    await stubPurchase(page, () => purchase());
    await page.goto("/app/answers/359");

    const doc = page.getByTestId("report-document");
    await expect(doc).toBeVisible();

    // The Summary is the clean lead paragraph the fixed parser derives.
    const summary = page.getByTestId("report-summary");
    await expect(summary).toHaveText(
      "The requested rear-yard variance is supportable on all three statutory tests.",
    );

    // The agent's chain-of-thought must never surface anywhere.
    await expect(doc).not.toContainText(/compile the findings/i);
    await expect(doc).not.toContainText(/gathered the key provisions/i);
    await expect(doc).not.toContainText(/sufficient information/i);

    // No stray markdown horizontal rule leaks into the summary or any block.
    await expect(summary).not.toContainText("---");
    await expect(page.getByTestId("report-blocks")).not.toContainText("---");
  });
});
