// Functional: ABS-365 — determination verdict tailored to the report type.
//
// The headline determination band is the most-read line on a report. Its
// *status* (colour band) is content-derived and shared across report types,
// but its *label* must be phrased in the report's own frame: a variance
// justification package concludes on statutory-test SUPPORTABILITY, not on
// use-permission ("Permitted with conditions" reads as a template artifact
// on a $299 variance deliverable).
//
// build_report (advisor.billing.report) now derives the label per question
// slug. This spec drives the real /app/answers view and stubs the purchase
// proxy at the network boundary with a payload mirroring what the fixed
// build_report emits (same pattern as the ABS-342 / ABS-366 report specs),
// asserting the rendered determination band carries the report-typed frame.

import { expect, test } from "../fixtures/test-env";
import type { Page, Route } from "@playwright/test";

type Report = Record<string, unknown>;

// A conditional variance package: content-derived status is `conditional`
// (the same brick band a permitted-use report would carry), but the label
// is the variance frame the build_report change produces.
function varianceReport(): Report {
  return {
    ref: "VJ-000365",
    report_type: "Variance justification package",
    address: "5686 Spring Garden Rd",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-07",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 29900,
    currency: "CAD",
    verdict: { status: "conditional", label: "Supportable with conditions" },
    summary:
      "A variance justification package for a reduced rear-yard setback at " +
      "5686 Spring Garden Rd.",
    blocks: [
      {
        type: "finding",
        status: "conditional",
        title: "Statutory tests",
        body: "The variance is minor and supportable, subject to conditions.",
      },
    ],
    footer:
      "This report was generated by ABS° and grounded in the HRM Regional " +
      "Centre Land Use By-law — 2024 consolidation. Reference VJ-000365, " +
      "issued 2026-07-07.",
  };
}

type Purchase = {
  id: number;
  question_slug: string;
  status: string;
  price_cents: number;
  currency: string;
  answer: string | null;
  report: Report | null;
  failure_reason: string | null;
  refinement_count: number;
  refinements_remaining: number;
  window_expires_at: string | null;
};

function purchase(overrides: Partial<Purchase> = {}): Purchase {
  return {
    id: 365,
    question_slug: "variance_justification",
    status: "captured",
    price_cents: 29900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: varianceReport(),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

async function stubPurchase(page: Page, get: () => unknown) {
  await page.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route) => json(route, get()),
  );
}

test.describe("verdict tailored to report type (ABS-365)", () => {
  test("a variance package concludes on supportability, not use-permission", async ({
    page,
  }) => {
    await stubPurchase(page, () => purchase());
    await page.goto("/app/answers/365");

    await expect(page.getByTestId("report-document")).toBeVisible();
    await expect(page.getByTestId("report-type")).toContainText(/variance/i);

    // The determination band: the status chip is still the content-derived
    // brick CONDITIONAL band, but the headline verdict is phrased on the
    // variance frame — not the generic "Permitted with conditions".
    await expect(page.getByTestId("report-verdict-chip")).toHaveText(
      "CONDITIONAL",
    );
    const verdict = page.getByTestId("report-verdict");
    await expect(verdict).toContainText("Supportable with conditions");
    await expect(verdict).not.toContainText(/permitted with conditions/i);
  });

  test("a clean-pass variance uses the three-statutory-tests headline", async ({
    page,
  }) => {
    await stubPurchase(page, () =>
      purchase({
        report: {
          ...varianceReport(),
          verdict: {
            status: "pass",
            label: "Supportable on all three statutory tests",
          },
        },
      }),
    );
    await page.goto("/app/answers/365");

    await expect(page.getByTestId("report-verdict-chip")).toHaveText("PASS");
    await expect(page.getByTestId("report-verdict")).toContainText(
      "Supportable on all three statutory tests",
    );
  });
});
