// Functional: ABS-368 report verification footer stamp + signature line.
//
// The design's verification footer is more than the prose traceability
// note — it also carries a rotated "VERIFIED" stamp box (year lifted off
// the report's own issued date, not "today") and an "ABS AGENT · AUTOMATED"
// signature line. Before this fix the footer rendered prose only. This
// spec drives the real /app/answers view (same stub pattern as ABS-342)
// and asserts all three pieces are present.

import { expect, test } from "../fixtures/test-env";
import type { Page, Route } from "@playwright/test";

type Report = Record<string, unknown>;

function report(overrides: Partial<Report> = {}): Report {
  return {
    ref: "DD-000368",
    report_type: "Zoning due-diligence summary",
    address: "1234 Elm Street",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-03",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 19900,
    currency: "CAD",
    verdict: { status: "conditional", label: "Permitted with conditions" },
    summary: "A preliminary zoning due-diligence summary for 1234 Elm Street.",
    blocks: [
      {
        type: "prose",
        title: "Notes",
        text: "This is a preliminary aid, not a substitute for a full memo.",
      },
    ],
    footer:
      "This report was generated by ABS° and grounded in the HRM Regional " +
      "Centre Land Use By-law — 2024 consolidation. Reference DD-000368, " +
      "issued 2026-07-03.",
    ...overrides,
  };
}

type Purchase = {
  id: number;
  question_slug: string;
  status: string;
  price_cents: number;
  currency: string;
  answer: string | null;
  report: Report | null;
  failure_reason: string | null;
  refinement_count: number;
  refinements_remaining: number;
  window_expires_at: string | null;
};

function purchase(overrides: Partial<Purchase> = {}): Purchase {
  return {
    id: 368,
    question_slug: "due_diligence",
    status: "captured",
    price_cents: 19900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: report(),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

async function stubPurchase(page: Page, get: () => unknown) {
  await page.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route) => json(route, get()),
  );
}

test.describe("report verification footer stamp + signature (ABS-368)", () => {
  test("footer renders the traceability note, VERIFIED stamp, and signature line", async ({
    page,
  }) => {
    await stubPurchase(page, () => purchase());
    await page.goto("/app/answers/368");

    const doc = page.getByTestId("report-document");
    await expect(doc).toBeVisible();

    const footer = page.getByTestId("report-footer");
    await expect(footer).toBeVisible();

    // Traceability note — the existing prose (ref + issued date).
    await expect(page.getByTestId("report-footer-note")).toContainText(
      "DD-000368",
    );

    // Signature line.
    await expect(page.getByTestId("report-signature")).toHaveText(
      "ABS AGENT · AUTOMATED",
    );

    // VERIFIED stamp — year lifted off the report's own issued date.
    const stamp = page.getByTestId("report-verified-stamp");
    await expect(stamp).toBeVisible();
    await expect(stamp).toContainText(/verified/i);
    await expect(stamp).toContainText("ABS · 2026");
  });

  test("stamp falls back to the current year when the report has no issued date", async ({
    page,
  }) => {
    await stubPurchase(page, () =>
      purchase({ report: report({ issued: "" }) }),
    );
    await page.goto("/app/answers/368");

    const stamp = page.getByTestId("report-verified-stamp");
    await expect(stamp).toBeVisible();
    await expect(stamp).toContainText(/ABS · \d{4}/);
  });
});
