// Functional: ABS-344 — unify report + conversation in one case workspace.
//
// The spec's premise is that a purchased report and the follow-up
// conversation about the same property are two faces of ONE /app workspace,
// not two routes. This spec drives the real /app shell (shared left case
// list + right parcel pane) with a report opened via ?report_id=, stubbing
// only the purchase-detail proxy at the network boundary (same pattern as
// the ABS-321 / ABS-342 answer specs). It asserts:
//   - a report-backed case opens inside /app with the CaseToolbar and the
//     report rendered in the center canvas;
//   - the CaseToolbar toggles the canvas report ↔ conversation;
//   - the app-header label tracks REPORT / CONVERSATION / GENERATING;
//   - the conversation face is seeded with the report + parcel context line;
//   - a conversation-only case (no report) hides the toggle entirely.

import { expect, openCaseViaApi, test } from "../fixtures/test-env";
import type { Page, Route } from "@playwright/test";

type Report = Record<string, unknown>;

function dueDiligenceReport(): Report {
  return {
    ref: "DD-000344",
    report_type: "Zoning due-diligence summary",
    address: "1234 Elm Street",
    zone_subtitle: "Established Residential, Type 1",
    issued: "2026-07-03",
    prepared_for: "Jordan Buyer",
    bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
    price_cents: 19900,
    currency: "CAD",
    verdict: { status: "conditional", label: "Permitted with conditions" },
    summary: "A preliminary zoning due-diligence summary for 1234 Elm Street.",
    blocks: [
      {
        type: "keyvals",
        title: "Zoning",
        items: [
          { k: "Zone", v: "ER-1" },
          { k: "Overlay", v: "Heritage Conservation" },
        ],
      },
    ],
    footer: "This report was generated by ABS° · reference DD-000344.",
  };
}

type Purchase = {
  id: number;
  question_slug: string;
  status: string;
  price_cents: number;
  currency: string;
  answer: string | null;
  report: Report | null;
  failure_reason: string | null;
  refinement_count: number;
  refinements_remaining: number;
  window_expires_at: string | null;
};

function purchase(overrides: Partial<Purchase> = {}): Purchase {
  return {
    id: 344,
    question_slug: "due_diligence",
    status: "captured",
    price_cents: 19900,
    currency: "CAD",
    answer: "Raw markdown fallback.",
    report: dueDiligenceReport(),
    failure_reason: null,
    refinement_count: 0,
    refinements_remaining: 3,
    window_expires_at: "2026-12-31T00:00:00Z",
    ...overrides,
  };
}

function json(route: Route, body: unknown, status = 200) {
  return route.fulfill({
    status,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

// Route the purchase-detail proxy (GET + the POST /answer auto-run). The
// sidebar's list endpoints are left to hit the real backend so the shared
// panes render exactly as in production.
async function stubPurchaseApi(
  page: Page,
  handlers: { get: () => unknown; answer?: (route: Route) => unknown },
) {
  await page.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route) => {
      const url = route.request().url();
      const method = route.request().method();
      if (method === "POST" && url.endsWith("/answer")) {
        return handlers.answer
          ? handlers.answer(route)
          : json(route, handlers.get());
      }
      return json(route, handlers.get());
    },
  );
}

test.describe("report + conversation unified workspace (ABS-344)", () => {
  test("open-from-purchase → report view → toggle to conversation", async ({
    page,
  }) => {
    await stubPurchaseApi(page, { get: () => purchase() });
    await page.goto("/app?report_id=344");

    // A report-backed case opens inside /app: shared left case list + right
    // parcel pane, with the CaseToolbar wrapping the center canvas.
    const toolbar = page.getByTestId("case-toolbar");
    await expect(toolbar).toBeVisible();
    await expect(page.getByTestId("case-toolbar-report")).toBeVisible();
    await expect(page.getByTestId("case-toolbar-conversation")).toBeVisible();

    // Center canvas shows the purchased report through the shared template.
    await expect(page.getByTestId("report-document")).toBeVisible();
    await expect(page.getByTestId("report-address")).toHaveText("1234 Elm Street");

    // The app-header label reads REPORT in report view.
    const label = page.getByTestId("workspace-label");
    await expect(label).toContainText("REPORT");

    // The report's Share / Export actions are present in report view.
    await expect(page.getByTestId("case-toolbar-share")).toBeVisible();
    await expect(page.getByTestId("case-toolbar-export")).toBeVisible();

    // Toggle to Conversation — same workspace, center canvas swaps.
    await page.getByTestId("case-toolbar-conversation").click();

    // Header label tracks the state.
    await expect(label).toContainText("CONVERSATION");

    // The conversation is seeded with the report + parcel context line, so
    // follow-ups read as grounded in the purchased answer.
    await expect(
      page.getByText(/Follow-ups are grounded in your purchased answer/i),
    ).toBeVisible();
    await expect(page.getByText(/1234 Elm Street/i).first()).toBeVisible();

    // The report canvas is hidden (not unmounted) behind the conversation.
    await expect(page.getByTestId("report-document")).toBeHidden();
    // Report-only actions drop away when the report face isn't showing.
    await expect(page.getByTestId("case-toolbar-share")).toHaveCount(0);

    // Toggle back to Report — canvas + label restore.
    await page.getByTestId("case-toolbar-report").click();
    await expect(label).toContainText("REPORT");
    await expect(page.getByTestId("report-document")).toBeVisible();
  });

  test("app-header shows GENERATING while the engine runs, then REPORT", async ({
    page,
  }) => {
    // First load: card authorized but the engine hasn't run — the report
    // face shows the reading indicator and the header reads GENERATING.
    let release = () => {};
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    await stubPurchaseApi(page, {
      get: () => purchase({ status: "authorized", answer: null, report: null }),
      answer: async (route) => {
        await gate; // hold the run open so GENERATING is observable
        return json(route, purchase({ status: "captured" }));
      },
    });
    await page.goto("/app?report_id=344");

    const label = page.getByTestId("workspace-label");
    await expect(label).toContainText("GENERATING");

    // Let the engine "finish" — the header flips to REPORT and the document
    // renders.
    release();
    await expect(label).toContainText("REPORT", { timeout: 10_000 });
    await expect(page.getByTestId("report-document")).toBeVisible();
  });

  test("a conversation-only case hides the toggle", async ({ page }) => {
    const { caseId } = await openCaseViaApi();
    await page.goto(`/app?case_id=${caseId}`);

    // The composer is the tell that we're in a live conversation case.
    await expect(page.getByPlaceholder(/Ask about this parcel/)).toBeVisible();

    // No report → no CaseToolbar / toggle at all.
    await expect(page.getByTestId("case-toolbar")).toHaveCount(0);
    await expect(page.getByTestId("workspace-label")).toContainText(
      "CONVERSATION",
    );
  });
});
