// Functional: ABS-384 — an already-purchased report of a now-disabled slug
// stays fully accessible forever.
//
// The per-report gate (ADVISOR_ENABLED_QUESTIONS) removes a slug from the
// menu and rejects NEW purchases, but the answer-delivery routes
// (get-purchase / reports-list / the /app report views) are deliberately
// left ungated. A customer who already bought a report must keep seeing it
// even after the operator disables that slug for new sales.
//
// Same network-boundary stubbing as the ABS-342 / ABS-346 report specs: the
// purchase-detail proxy is faked (a captured due_diligence report) and the
// menu is stubbed to EXCLUDE due_diligence (the disabled state), while the
// shared /app shell and /app/print surface drive for real.

import { expect, test } from "../fixtures/test-env";
import type { BrowserContext, Route } from "@playwright/test";

const REPORT = {
  ref: "DD-000384",
  report_type: "Zoning due-diligence summary",
  address: "1234 Elm Street",
  zone_subtitle: "Established Residential, Type 1",
  issued: "2026-07-14",
  prepared_for: "Jordan Buyer",
  bylaw_version: "HRM Regional Centre Land Use By-law — 2024 consolidation",
  price_cents: 19900,
  currency: "CAD",
  verdict: { status: "conditional", label: "Permitted with conditions" },
  summary: "A preliminary zoning due-diligence summary for 1234 Elm Street.",
  blocks: [
    {
      type: "finding",
      status: "conditional",
      title: "Rear-yard setback",
      body: "The existing structure sits within the minimum rear-yard setback.",
    },
  ],
  footer: "This report was generated by ABS° · reference DD-000384.",
};

const PURCHASE = {
  id: 384,
  question_slug: "due_diligence",
  status: "captured",
  price_cents: 19900,
  currency: "CAD",
  answer: "Raw markdown fallback.",
  report: REPORT,
  failure_reason: null,
  refinement_count: 0,
  refinements_remaining: 3,
  window_expires_at: "2026-12-31T00:00:00Z",
};

// The captured purchase renders on both /app?report_id and the /app/print
// popup (a separate Page), so route at the context level.
async function stubPurchaseApi(context: BrowserContext) {
  await context.route(
    /\/api\/billing\/questions\/purchases\/\d+(\/(answer|refine))?$/,
    (route: Route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(PURCHASE),
      }),
  );
}

// The menu no longer carries the due_diligence slug — the operator disabled
// it for new sales.
async function stubDisabledMenu(context: BrowserContext) {
  await context.route("**/api/billing/questions", async (route) => {
    const resp = await route.fetch();
    const body = await resp.json();
    body.questions = (
      body.questions as Array<{ slug: string }>
    ).filter((q) => q.slug !== "due_diligence");
    await route.fulfill({ response: resp, json: body });
  });
}

test.describe("purchased report of a disabled slug (ABS-384)", () => {
  test("the captured report still renders at /app?report_id even though its slug is disabled", async ({
    page,
    context,
  }) => {
    await stubDisabledMenu(context);
    await stubPurchaseApi(context);

    await page.goto("/app?report_id=384");

    // The purchased report renders in full despite the slug being pulled
    // from the sale menu.
    await expect(page.getByTestId("report-document")).toBeVisible();
    await expect(page.getByTestId("report-type")).toContainText(
      /due-diligence/i,
    );
  });

  test("the disabled-slug report still prints at /app/print", async ({
    page,
    context,
  }) => {
    await stubDisabledMenu(context);
    await stubPurchaseApi(context);

    await page.goto("/app/print?report_id=384");

    await expect(page.getByTestId("report-print")).toBeVisible();
    await expect(page.getByTestId("report-document")).toBeVisible();
    await expect(page.getByTestId("report-type")).toContainText(
      /due-diligence/i,
    );
  });
});
