// /terms — public-facing summary of the Terms of Use.
//
// The binding contract is the document served via /api/terms (source at
// docs/TERMS_AND_CONDITIONS.md), shown on the click-wrap acceptance
// screen at first sign-in (ABS-18). This page is a plain-English
// summary of that contract — *not* a second, contradictory short-form.
//
// If you change the binding document, mirror the change here. The two
// must not drift.

import { LegalShell, Section } from "@/components/marketing/legal-shell";

const SECTIONS: Section[] = [
  {
    id: "tm-1",
    n: "1.0",
    t: "About this summary",
    body: [
      {
        k: "p",
        v: "This page summarizes the Terms of Use of the ABS application. The summary is informational. The binding agreement is the full document shown on the acceptance screen at first sign-in and re-served at /app/terms inside the app.",
      },
      {
        k: "p",
        v: "By creating an account, signing in, or transmitting data to the service, you agree to that binding document.",
      },
    ],
  },
  {
    id: "tm-2",
    n: "2.0",
    t: "What ABS is",
    body: [
      {
        k: "p",
        v: "ABS is a research tool. It ingests and indexes municipal land-use bylaws and related public materials, retrieves the parts relevant to a parcel or question you supply, and uses a large language model to compose a reading with citations back to the source text.",
      },
      {
        k: "p",
        v: "During private beta the service is limited to the Halifax Regional Centre Land Use By-law. See the Coverage page for the current scope.",
      },
    ],
  },
  {
    id: "tm-3",
    n: "3.0",
    t: "Not legal or professional advice",
    body: [
      {
        k: "p",
        v: "ABS does not give legal advice, planning advice, engineering advice, architectural advice, surveying advice, or any other form of professional advice. Using ABS does not create any solicitor-client, planner-client, or other professional relationship between you and us.",
      },
      {
        k: "note",
        v: "Always verify a reading with HRM Planning (or a licensed professional) before relying on it for a permit application or any irreversible decision. Do not present a reading to a third party as professional advice from us.",
      },
    ],
  },
  {
    id: "tm-4",
    n: "4.0",
    t: "AI errors are real",
    body: [
      {
        k: "p",
        v: "Readings are generated by AI and retrieval systems and can be wrong in confident-sounding ways: hallucinated citations, wrong-zone or wrong-overlay matches, stale consolidations, miscalculated setbacks or coverage figures, and so on.",
      },
      {
        k: "p",
        v: "The binding Terms list these failure modes in detail and require you to independently verify every output before acting on it.",
      },
    ],
  },
  {
    id: "tm-5",
    n: "5.0",
    t: "Acceptable use",
    body: [
      { k: "p", v: "Things you agree not to do:" },
      {
        k: "ul",
        v: [
          "Present ABS output to a third party as your own professional advice unless you are independently licensed and take full responsibility.",
          "Reverse-engineer the service, circumvent rate limits or billing, or probe for vulnerabilities.",
          "Use ABS to train, fine-tune, or build a competing product.",
          "Resell or bulk-redistribute the service or its output without our prior written consent.",
        ],
      },
    ],
  },
  {
    id: "tm-6",
    n: "6.0",
    t: "Liability cap",
    body: [
      {
        k: "p",
        v: "The binding Terms cap our total liability for any claim arising out of the service at the greater of (a) the fees you actually paid us in the 12 months before the claim, or (b) CAD $100. Non-excludable consumer-protection rights under Nova Scotia law are preserved.",
      },
      {
        k: "p",
        v: "The service is provided AS-IS with no warranties of accuracy, completeness, fitness, or uninterrupted operation.",
      },
    ],
  },
  {
    id: "tm-7",
    n: "7.0",
    t: "Payment & cancellation",
    body: [
      {
        k: "p",
        v: "Paid plans are billed in CAD. On deployments where billing is enabled, you can cancel at any time from the Billing page; the cancellation takes effect at the end of the current billing period.",
      },
      {
        k: "p",
        v: "On beta deployments where the purchase flow is dormant, an operator may grant a starting turn balance manually.",
      },
    ],
  },
  {
    id: "tm-7a",
    n: "7a",
    t: "Paid answers — still research",
    body: [
      {
        k: "p",
        v: "Some queries are designated as priced questions and carry a fee. Paying that fee does not change what the answer is: it is a research output from an automated bylaw-analysis tool, not a determination by any municipality, and not the professional opinion of a licensed planner, lawyer, engineer, architect, or surveyor.",
      },
      {
        k: "note",
        v: "Every paid answer carries a disclaimer to this effect. The same verification obligation from section 3.0 applies — independently confirm the output with HRM Planning (or a qualified professional) before relying on it for any permit application or irreversible decision.",
      },
    ],
  },
  {
    id: "tm-8",
    n: "8.0",
    t: "Governing law",
    body: [
      {
        k: "p",
        v: "The binding Terms are governed by the laws of Nova Scotia and the laws of Canada applicable there. Disputes are heard in the courts of Nova Scotia sitting in Halifax. The binding Terms also contain a class-action waiver, subject to non-excludable consumer-protection rights.",
      },
    ],
  },
  {
    id: "tm-9",
    n: "9.0",
    t: "Changes",
    body: [
      {
        k: "p",
        v: "Material changes to the binding Terms trigger a re-acceptance prompt on next login. This summary will be updated to match.",
      },
      {
        k: "p",
        v: "Questions about these Terms: info@agenticbylawsystems.com.",
      },
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalShell
      kicker="POLICY · TERMS OF USE"
      title="Terms of use."
      sub="A plain-English summary of the agreement between you and ABS. The binding version is the document you accept on the sign-in screen — please read it there."
      plainSummary="ABS produces research, not legal advice — verify every reading with HRM Planning before acting on it, because AI can be confidently wrong. Our total liability is capped at the greater of the fees you paid us in the last 12 months or CAD $100, and the agreement is governed by Nova Scotia law. The binding document is the one you accept at sign-in; this page is a summary, not a substitute."
      consolidatedAt="May 21, 2026"
      version="beta-1"
      sections={SECTIONS}
    />
  );
}
